### ISSUE TITLE
[Q] How to Increase performance ?

### ISSUE THREAD

**Issue by am2222** [pramsey/pgsql-ogr-fdw#100]
Hi,
I have a SQL Database which includes lots of data.I want to join these data to spatial data in my postsql database. (My sql database only has non spatial data)
Any way.I have connected those servers using ogr_fdw. They works fine.
I have created an sql view which I can improve performance.
I have a question. Is it evel logical to use ogr fdw? and also what about performance?
How we can increase it while we have faced lots of data?
Thank you

**Comment by pramsey** [comment]
Your best bet us to use ogr_fdw in conjunction with a materialized view that queries the foreign table. That way you can easily replicate your data locally at regular intervals and do the join completely locally where it will be much faster. Core improvements to ogr_fdw for connection caching and reduced query width would probably also help.
