### ISSUE TITLE
Override projection

### ISSUE THREAD

**Issue by stev-0** [pramsey/pgsql-ogr-fdw#102]
Would be nice if there was a way to override projection. I am thinking with .shp files especially, what with the spec being so messed up!

I think ogr (but not sure) that ogr is barfing on my wierd .prj definition, and is not picking up the shp geometry. The ogrinfo in the postgis version I am using gives me (as an example feature)

`POINT (544052.00197613728 197618.00169067297 0)` so it is picking up the geometry but not the projection. The geometry is then not copied across to the foreign table.

I am using an older version so perhaps this has been solved but I haven't seen any issues relating to it.

**Comment by pramsey** [comment]
I really don't understand the issue. Can you try and explain in more detail when actions you are taking and what results you are getting?

**Comment by stev-0** [comment]
I run ogr_fdw_info and get:

CREATE SERVER myserver
  FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
    datasource 'blah"
    format 'ESRI Shapefile' );

CREATE FOREIGN TABLE efdc_ancient_trees_point (
  fid integer,
  geom geometry,
  survey_dat date,
 blah.... )
  SERVER myserver
  OPTIONS ( layer 'EFDC Ancient Trees_point' );

But there is no geometry in the geom field in Postgis (everything else is fine).

When I run ogrinfo (see above) it clearly is reading the correct geometry but it appears that geometry does not have a projection. Whether this is the reason it's not coming through to the geom field in postgis I don't know. So maybe I should have split this into two:

1. The problem above, which I am not sure how to debug or whether this is OGR specific, and;

2. More generally, it would be good to be able to override what OGR thinks the geometry is and specify it

If you think 1. could be a bug with ogr_fdw I can create a new issue and tidy this one up.

**Comment by pramsey** [comment]
Old version shouldn't care about projection, new version should carry it if it has it, but otherwise also shouldn't care. Can you share your file?

**Comment by stev-0** [comment]
I think you're right, it's the format of the file. When resaved by QGIS it doesn't seem to be a problem. I can't really post it publically, but I can find an email address for you, is it worth sending it to you. Could well be OGR where the error handling is required though.

**Comment by pramsey** [comment]
If you can send a file or link to me, feel free to remove private attributes, etc, as long as the file still exhibits the problem. pramsey at cleverelephant doht ca

**Comment by pramsey** [comment]
Would love to fix, but closing out until I get some data to use for testing.

**Comment by stev-0** [comment]
Have now sent the file. Thanks

**Comment by pramsey** [comment]
OK, so still not seeing what you are seeing... or maybe there is just a miscommunication. Based on just the definitions provided by `ogr_fdw_info` I create a server and table and get the following back. There's no SRID, sure, but then I didn't define one in the table def'n.
```
fdw=# select st_srid(geom),st_astext(geom) from trees_point limit 5;
 st_srid |                   st_astext                   
---------+-----------------------------------------------
       0 | POINT Z (556916.004021501 211496.998869057 0)
       0 | POINT Z (556872.997782798 211406.004915805 0)
       0 | POINT Z (556920.002876135 211406.004915805 0)
       0 | POINT Z (553370.001123384 206665.002013769 0)
       0 | POINT Z (552066.00348494 205240.999630211 0)
(5 rows)
```
If I want to have a table which forces an SRID onto the inputs, I can do that, just by adding the information to the SQL.
```
CREATE FOREIGN TABLE trees_point (
  fid bigint,
  geom Geometry(PointZ, 27700),
  survey_dat date,
  vt_survey_ varchar,
  parish varchar,
  species varchar,
  girth__m_ real,
  form varchar,
  subform varchar,
  tree_statu varchar,
  grid varchar,
  grid_x varchar,
  grid_y varchar,
  grid_ref varchar,
  access varchar,
  stand_fall varchar,
  alive_dead varchar,
  gr_x real,
  gr_y real
) SERVER myserver
OPTIONS (layer 'Trees_point');
```
And now the SRID is applied to the incoming geometries
```
fdw=# select st_srid(geom),st_astext(geom) from trees_point limit 5;
 st_srid |                   st_astext                   
---------+-----------------------------------------------
   27700 | POINT Z (556916.004021501 211496.998869057 0)
   27700 | POINT Z (556872.997782798 211406.004915805 0)
   27700 | POINT Z (556920.002876135 211406.004915805 0)
   27700 | POINT Z (553370.001123384 206665.002013769 0)
   27700 | POINT Z (552066.00348494 205240.999630211 0)
(5 rows)
```
Which means I can reproject if I like
```
fdw=# select st_srid(geom),st_astext(st_transform(geom,4326)) from trees_point limit 5;
 st_srid |                           st_astext                           
---------+---------------------------------------------------------------
   27700 | POINT Z (0.27326511264441 51.780141286797 45.8745559947565)
   27700 | POINT Z (0.272601133710946 51.7793358478836 45.8746023802087)
   27700 | POINT Z (0.273281932996707 51.779322681303 45.8736525792629)
   27700 | POINT Z (0.219773612272253 51.7377113636922 45.9021936198696)
   27700 | POINT Z (0.2002820792919 51.7252724624136 45.9154192423448)
(5 rows)
```
Intriguingly, there's an elevation shift in that transform as well, but that's a separate concern from the FDW one.

**Comment by robe2** [comment]
Speaking of overriding.  ogr_fdw is guessing wrong on SRID for me.  How does it decide on that.


My .prj file from city of boston looks like this:
`PROJCS["NAD_1983_StatePlane_Massachusetts_Mainland_FIPS_2001_Feet",GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["False_Easting",656166.6666666665],PARAMETER["False_Northing",2460625.0],PARAMETER["Central_Meridian",-71.5],PARAMETER["Standard_Parallel_1",41.71666666666667],PARAMETER["Standard_Parallel_2",42.68333333333333],PARAMETER["Latitude_Of_Origin",41.0],UNIT["Foot_US",0.3048006096012192]]`


When I run:

`gdalsrsinfo city_council_districts.shp`

I get this output:

`
PROJ.4 : '+proj=lcc +lat_1=41.71666666666667 +lat_2=42.68333333333333 +lat_0=41 +lon_0=-71.5 +x_0=199999.9999999999 +y_0=750000 +datum=NAD83 +units=us-ft +no_defs '

OGC WKT :
PROJCS["NAD_1983_StatePlane_Massachusetts_Mainland_FIPS_2001_Feet",
    GEOGCS["GCS_North_American_1983",
        DATUM["North_American_Datum_1983",
            SPHEROID["GRS_1980",6378137.0,298.257222101]],
        PRIMEM["Greenwich",0.0],
        UNIT["Degree",0.0174532925199433]],
    PROJECTION["Lambert_Conformal_Conic_2SP"],
    PARAMETER["False_Easting",656166.6666666665],
    PARAMETER["False_Northing",2460625.0],
    PARAMETER["Central_Meridian",-71.5],
    PARAMETER["Standard_Parallel_1",41.71666666666667],
    PARAMETER["Standard_Parallel_2",42.68333333333333],
    PARAMETER["Latitude_Of_Origin",41.0],
    UNIT["Foot_US",0.3048006096012192]]

`
But when I check ST_SRID:

`SELECT st_srid(geom) 
  FROM shps.city_council_districts
limit 1;
`

I get back 4269

It should be 2249

which when I query spatial_ref_sys gives:

`+proj=lcc +lat_1=42.68333333333333 +lat_2=41.71666666666667 +lat_0=41 +lon_0=-71.5 +x_0=200000.0001016002 +y_0=750000 +datum=NAD83 +units=us-ft +no_defs `

**Comment by pramsey** [comment]
I just use OSRAutoIdentifyEPSG() and hope GDAL comes up with the right answer. Apparently not always. BTW, don't trespass on other people's tickets :)

**Comment by pramsey** [comment]
Will close this out until new info arrived.
