### ISSUE TITLE
PostgreSQL 9.6 Parallel thread - invalid cache ID

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#104]
So I've got PostGIS 2.3 installed on my PostgreSQL 9.6beta1 and latest ogr_fdw.

And I was crazy enough to force parallelization just to see what would happen and then I ran this query on my ogr_fdw foreign table:

```
SELECT st_srid(geom) FROM shps.city_council_districts limit 1;

```

And I get a dialog alert in pgAdmin:

> ERROR: invalid cache ID: 11

> CONTEXT: parallel worker, PID 2240

Not sure if this is a bug in 9.6 or something needs changing in ogr_fdw

**Comment by pramsey** [comment]
Stop doing terrible things.

**Comment by StepanYankevych** [comment]
I have the same error on many tables 
for example 
`select count(1) from client_order where date_id = 20170301;`
PostgreSQL 9.6.1 under Redhat

Here is part of log 

> < 2017-03-07 08:57:45.312 EST >ERROR: invalid cache ID: 41 
> < 2017-03-07 08:57:45.312 EST >ERROR: invalid cache ID: 41 
> < 2017-03-07 08:57:45.312 EST >ERROR: invalid cache ID: 41 
> < 2017-03-07 08:57:45.312 EST >ERROR: invalid cache ID: 41 
> < 2017-03-07 08:57:45.312 EST >ERROR: invalid cache ID: 41 
> < 2017-03-07 08:57:45.312 EST [unknown] SELECT>ERROR: invalid cache ID: 41 
> < 2017-03-07 08:57:45.312 EST [unknown] SELECT>CONTEXT: parallel worker 
> < 2017-03-07 08:57:45.312 EST [unknown] SELECT>STATEMENT: select count(1)
