### ISSUE TITLE
ogr_fdw_info unable to handle shapefiles with leading digits in filenames?

### ISSUE THREAD

**Issue by apiszcz** [pramsey/pgsql-ogr-fdw#107]
PostGres 9.5.3, PostGIS 2.2.2, Windows 10/64, ogr_fdw 1.0

ogr_fdw                      | 1.0             | 1.0               | foreign-data wrapper for GIS data access

Is the foreign table name unable to handle leading digits? Is there an option or work around to have ogr_fdw_info handle filenames starting with digits?

--- EXAMPLE : FAIL

WITH DIGITS LEADING FEATURE NAME

C:\p\v>lib\pgsql\bin\ogr_fdw_info -s _e\01_e\shp\20160802T154003_e_000100000.shp -l 20160802T154003_e_000100000

CREATE SERVER myserver
  FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
    datasource '_e\01_ee\shp\20160802T154003_e_000100000.shp',
    format 'ESRI Shapefile' );

CREATE FOREIGN TABLE n22222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222_(S (
  fid integer,
  geom geometry,
  ex varchar,
  ey varchar
 )
  SERVER myserver
  OPTIONS ( layer '20160802T154003_e_000100000' );

EXAMPLE : SUCCESS

WITH NON DIGIT CHARACTER LEADING FEATURE NAME

C:\p\v>lib\pgsql\bin\ogr_fdw_info -s _e\01_e\shp\e.shp -l e

CREATE SERVER myserver
  FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
    datasource '_e\01_e\shp\e.shp',
    format 'ESRI Shapefile' );

CREATE FOREIGN TABLE e (
  fid integer,
  geom geometry,
  ex varchar,
  ey varchar )
  SERVER myserver
  OPTIONS ( layer 'e' );

**Comment by pramsey** [comment]
This failure in the laundering code (no, PgSQL cannot handle tables with initial digits, so the table name needs to be laundered into something legal) is fixed in the current code. You'll want a more recent build. You can fix your proximate problem just by slightly altering the SQL you use, 
```sql
CREATE SERVER myserver
FOREIGN DATA WRAPPER ogr_fdw
OPTIONS (
datasource '_e\01_ee\shp\20160802T154003_e_000100000.shp',
format 'ESRI Shapefile' );
CREATE FOREIGN TABLE n20160802T154003_e_000100000 (
fid integer,
geom geometry,
ex varchar,
ey varchar
)
SERVER myserver
OPTIONS ( layer '20160802T154003_e_000100000' );
```
So the file name you reference in the 'layer' OPTION is the normal digits and the table name has a prefix of 'n' to make it legal for PgSQL.

**Comment by apiszcz** [comment]
Paul, thank you for the confirmation of my observation.
I grabbed the compiled windows binary from a link at this page,
http://postgis.net/windows_downloads/
I see ogr_fdw 1.0.1. however the only windows compiled binary I see is, and
this is version 1.0 ogr_fdw
http://download.osgeo.org/postgis/windows/pg95/postgis-bundle-pg95-2.2.2x64-2.zip

**Comment by apiszcz** [comment]
Thanks I located the ogr_fdw 1.0.1 in stackbuilder 3.1.1.

> PostGIS 2.2 bundle includes PostGIS 2.2.2, pgRouting 2.2.2, ogr_fdw 1.0.1 spatial foreign data wrapper extension, and pgPointcloud 1.1.0dev.

I'm seeing the same issue using 1.0.1.

**Comment by pramsey** [comment]
Sorry, you need 1.0.2 for the fix.
