### ISSUE TITLE
Typmoded geometry

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#11]
Another feature request  and not sure this is feasible so dismiss if not.

I assume this is possible to infer from ogr since as I recall when I import with ogr it does create typmoded geometries.

Currently -- ogr_fdw_info gives me something like this:

```
CREATE FOREIGN TABLE mbta_node (
  fid integer,
  geom geometry,
  objectid integer,
  station varchar,
  line varchar )
  SERVER myserver
  OPTIONS ( layer 'MBTA_NODE' );
```

and then I got to go look at the source to figure out I can do this geom geometry(POINT,26986), but
unfortunately though I can get away with this and it registers correctly in geometry_columns, 

my geometries when I do ST_SRID(geom) are still 0.  So my spatial joins are kind of ugly cause I have to do a ST_SetSRID then possibly and additional ST_Transform or create a view wrapper around my foreign table.

It would be nice if it both the ogr_fdw could infer the SRID and also if ogr_fdw_info could produce the corresponding meta data.

**Comment by pramsey** [comment]
OGR doesn't provide any means of accessing an SRID via the C API, so for the moment the answer kind of has to be "no". You'll just have to manually ensure you use the right typmod information when creating your tabel

**Comment by robe2** [comment]
Using the right typmoded geometry when creating the table doesn't work.  I had tried changing the foreign table definition to say geom geometry(POINT,26986).  And what happens is as soon as I do a join with another table, I get the annoying message and mixed SRIDs  0 and 26986 can't be mixed.  If you do a ST_SRID(geom) on a ogr_fdw table regardless your typmod -- it will return 0.    

Anyway sounds like it's an issue that can't be easily fixed.  So at best we just have to note this as a limitation so people don't go around trying to define their foreign table geom as geom(POINT,26986) or whatever only to find out when they use it with other tables it doesn't work.

As a work around, I just end up wrapping the table in a view with something like:

```
CREATE OR REPLACE VIEW vw_mbta_node AS
SELECT objectid, ST_SetSRID(geom, 26986)::geometry(POINT,26986), station, line
FROM mbta_node;

```

Which isn't too big of a deal as long as I know the issue before hand.

**Comment by pramsey** [comment]
Right now geometries are created w/o regard to the typmod information, but it may be possible to read it off the table and apply it to the objects (maybe) so things work out OK in the end.
