### ISSUE TITLE
ogr_fdw gdb support ?

### ISSUE THREAD

**Issue by apiszcz** [pramsey/pgsql-ogr-fdw#110]
A single gdb connection works fine. With  shapefiles which reside in a single folder the ogr_fdw SERVER accesses all files. Is it possible to access multiple GDB's in the same folder?

**Comment by pramsey** [comment]
no, each gdb is itself a folder that can contain multiple layers, so OGR is going to have to address them one at a time, which means one connection per file.  Or you could build a VRTLayer than exposes all the layers as if they were in one container http://www.gdal.org/drv_vrt.html
