### ISSUE TITLE
Connection to SQL Server sometimes causes crash in PostgreSQL 9.6rc1

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#112]
@pramsey  no need to do anything until I dissect this more for you :). Just putting this in here so I don't forget.

I'm getting a crash in PostgreSQL 9.6rc1, windows 64-bit, running with GDAL 2.1.0 and ogrfdw 1.0.2.

On my PostgreSQL 9.5 instance running ogrfdw 1.0.1 and GDAL 2.0.2 this works fine.  Needless to say I have to dissect which newr thing is causing it as it could be in ogrfdw, PostgreSQL or GDAL.

I have a sql server connection that looks something like this:

```

CREATE SERVER ntcedit2
  FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
    datasource 'ODBC:pgntc/***@MSSQL_NTCEDIT',
    format 'ODBC' );


-- crashes in 9.6 after returning 399 tables will be created, but in 9.5 says 399 tables will be created and creates them

IMPORT FOREIGN SCHEMA ogr_all FROM SERVER ntcedit2 INTO staging_mssql;
```

The error in the 9.6 logs shows:

```
invalid record length at 0/1967BA8: wanted 24, got 0
```

So it seems the issue is happening on the creation.  I'll investigate further.  If I itemize just the tables I want, it works fine.  So must be in one of the other tables, perhaps a system table being pulled in

**Comment by robe2** [comment]
I was hoping this issue would go away with upgrading to GDAL 2.1.3 and PostgreSQL 9.6.1 64-bit

I ruled out it being one of the tables in question because if I do:

```
CREATE SCHEMA staging_mssql;
IMPORT FOREIGN SCHEMA "dbo" FROM SERVER ntcedit2 INTO staging_mssql;
IMPORT FOREIGN SCHEMA "sys" FROM SERVER ntcedit2 INTO staging_mssql;
IMPORT FOREIGN SCHEMA "INF" FROM SERVER ntcedit2 INTO staging_mssql;

```

That brings in 406 foreign tables total.  All are accounted for.

If I run:
```

CREATE SCHEMA staging_mssql;
IMPORT FOREIGN SCHEMA "dbo" FROM SERVER ntcedit2 INTO staging_mssql;

```

I get notice:

```

NOTICE:  Number of tables to be created 406
********** Error **********

```

**Comment by pramsey** [comment]
Isn't the second example the same as the first? why would doing two subsequent requests change things?

**Comment by robe2** [comment]
Oops sorry that was a typo, corrected.

**Comment by pramsey** [comment]
Wondering if the fix for #125 picked up this one as well

**Comment by robe2** [comment]
I'll give it a try later and let you know.

**Comment by robe2** [comment]
I don't have quite the same exact database and now I have GDAL 2.2.1 installed.  I have more tables now.  This might have fixed it though because when I did in pg10 beta2 I get this and yes all tables are there.  Which is more
than I had in prior database.

`

NOTICE:  Number of tables to be created 638
Query returned successfully with no result in 2.9 secs.

`

I haven't retested on 9.6 though and don't recall if I ever tested this on 10.  I'll reopen if I still see issue on 9.6 under VC++, but I'll assume it's fixed.
