### ISSUE TITLE
Push down aggregates

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#115]
PostgreSQL 10 now has ability to push down aggregates in FDW api.  Was wondering if this is something ogr_fdw can possibly take advantage of.

https://www.depesz.com/2016/10/25/waiting-for-postgresql-10-postgres_fdw-push-down-aggregates-to-remote-servers/

**Comment by pramsey** [comment]
Not really, OGR just has its limited SQL filtering syntax and that's about it, *except* for some of the SQL backed formats, but at that point you might as well just use a specific database FDW rather than something as generic as OGR.
