### ISSUE TITLE
xlsx/xls provide a way to reference column by index and able to skip first n rows

### ISSUE THREAD

**Issue by zcattacz** [pramsey/pgsql-ogr-fdw#116]
The current version is not CJK character friendly (the header definition always get garbaled, though the CJK characters in table values work fine.). This is very frustrating. since the data file is not always in our control.
I have no interest in CJK charater support in header, since most of the time the header is not concise for db table column name. It would be more useful in more cases, if ogr-fdw can support referencing by column index and preferably skip n rows. That way, it will work just fine without processing sheet headers.

**Comment by pramsey** [comment]
Can you do this (i'm not 100% sure what "this" is) using plain ogr2ogr? If not, then this firstly is a feature request for OGR/GDAL. The FDW can only do what the underlying library can do.
