### ISSUE TITLE
Can not connect to netcdf source with ubuntu 16.04, postgres 9.6, postgis 2.3 and gdal 2.1.2

### ISSUE THREAD

**Issue by ardilgulez** [pramsey/pgsql-ogr-fdw#117]
Hey,

I'm using postgres 9.6 with postgis 2.3 and gdal 2.1.2, but I can not connect to a .nc file as a source.

```
$ gdalinfo --version
GDAL 2.1.2, released 2016/10/24

$ ogrinfo --version
GDAL 2.1.2, released 2016/10/24

./ogr_fdw_info -s /tmp/test/netcdf/test.nc 
ERROR 1: Could not conect to source '/tmp/test/netcdf/test.nc'
```
Did I miss anything with GDAL installation or with fdw? GDAL installation suggested that netcdf was supported during ./configure phase.

Thanks in advance.

**Comment by pramsey** [comment]
Well, we don't support rasters, so that could be it.
