### ISSUE TITLE
Get OGR_STYLE field from foreign table

### ISSUE THREAD

**Issue by nextstopsun** [pramsey/pgsql-ogr-fdw#118]
Is it possible to get `OGR_STYLE` as a foreign table column? I need it to get DXF MTEXT objects styling. In `ogrinfo` or `ogr2ogr` I can return it with ```-sql "select *, OGR_STYLE from entities"```. Is it possible to pass `-sql` to server options or retrieve `OGR_STYLE` column somehow?

**Comment by pramsey** [comment]
No, looks like it is not possible. OGR FDW will to open options, but it seems like the only way to get at OGR_STYLE is vis the [OGRFeature::GetStyleString](http://www.gdal.org/classOGRFeature.html#a54c179e53eb6eddb657dd392a87cccab) method. That would require a new option and some new code in the FDW itself. I'll leave this as an enhancement ticket for now.
