### ISSUE TITLE
Empty String As Null Config Option

### ISSUE THREAD

**Issue by apjoseph** [pramsey/pgsql-ogr-fdw#121]
Would it be possible to add an option to convert empty strings to null upon import? GDAL seems to have no global config option for this, nor does the shapefile driver. I believe shp2pgsql does this by default, but might be mistaken. Adding such an option could save users countless hours of immiseration.

**Comment by pramsey** [comment]
This is a feature request for GDAL, not for the FDW binding. My job is just to bind GDAL and the database. Mucking with the data is GDAL's job. I'm sure it's a reasonable GDAL feature request!
