### ISSUE TITLE
Oracle Support?

### ISSUE THREAD

**Issue by jonrmayer** [pramsey/pgsql-ogr-fdw#122]
Apologies for my ignorance but is it possible for ogr_fdw to use the OCI data format?

**Comment by pramsey** [comment]
If your GDAL/OGR is appropriately compiled.

**Comment by robe2** [comment]
If you have GDAL enabled with ODB, you can alternatively go via the ODBC driver if OCI is not directly enabled.  ODBC will work on both windows and Unix if your system has the appropriate ODBC OCI for oracle.

**Comment by robe2** [comment]
@pramsey  shouldn't you close this out.  This seems like more of a question than a real issue.
