### ISSUE TITLE
How to compile with freexl library

### ISSUE THREAD

**Issue by onemojofilter** [pramsey/pgsql-ogr-fdw#137]
I am trying to get pgsql-ogr-fdw to read from an Excel spreadsheet. I am running Oracle Linux 6.7 and Postgres 9.4. I downloaded, built and installed the freexl library. I am not completely certain I've done this correctly. 

I have appended a reference to freexl to the following line:

ogr_fdw_info$(X): ogr_fdw_info.o ogr_fdw_common.o stringbuffer.o
        $(CC) $(CFLAGS) -o $@ $^ $(LIBS)  -lfreexl

When I type ogr_fdw_info -f
I get:
Supported Formats:

That is, zero supported formats. I was under the impression that out of the box there would be several formats listed. Can you give me any guidance on how to get this working?

**Comment by pramsey** [comment]
You're working one level too close to the database. You need to compile gdal with the format support you want, and confirm it works using ogrinfo to read a spreadsheet. Once you've got that you can link ogr-fdw to your new gdal.

**Comment by onemojofilter** [comment]
Thanks!
