### ISSUE TITLE
Use ogr_fdw to write new files from PostgreSQL tables ?

### ISSUE THREAD

**Issue by mdouchin** [pramsey/pgsql-ogr-fdw#139]
Hi, 

I wonder if it is possible to use ogr_fdw with the updatable option to write (or overwrite) any file on disk ( / tmp/ for example). The idea is to export data from PostgreSQL into Shapefile or any other format, without the need to pre-create the empty Shapefile beforehand.

Any hint on this ?
Thanks a lot for your work for ogr_fdw

**Comment by pramsey** [comment]
Nope, FDW has no allowance for creating remote tables. Use `ogr2ogr` or `pgsql2shp`, you'll be happier in the long run.

**Comment by mdouchin** [comment]
thanks for your answer. Indeed, it was a bit cumbersome, but for some users, it makes sense to "stay inside" PostgreSQL. I personnaly used ogr2ogr for years with much love ;)
