### ISSUE TITLE
regression failure invalid byte sequence

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#141]
Okay I have this data, I know it's bad.  It's got some sort of control character in the JOBCLS column.

But prior to ogr_fdw 1.0.4 (I know it works with ogr_fdw 1.0.2, have to check 1.0.3), this data used to load.

I ruled out GDAL as being the culprint since compiling older ogr_fdw 1.0.2 with GDAL 2.2.2 works, but ogr_fdw 1.0.4 (and master do not).

Attached is the data reduced to the offending bit.

[job_bad.zip](https://github.com/pramsey/pgsql-ogr-fdw/files/1412465/job_bad.zip)

Steps to reproduce issue:

`
CREATE SERVER svr_csv
   FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (datasource 'C:/fdw_data/csv',format 'CSV');

DROP SCHEMA IF EXISTS csv CASCADE;
CREATE SCHEMA csv;
IMPORT FOREIGN SCHEMA ogr_all LIMIT TO (job_bad) FROM SERVER svr_csv INTO csv;

SELECT * FROM csv.job_bad;
`

outputs:

ERROR:  invalid byte sequence for encoding "UTF8": 0x96

**Comment by pramsey** [comment]
Yeah, so it looks like OGR doesn't actually fully obey its internal "[strings will be UTF-8](https://trac.osgeo.org/gdal/wiki/rfc23_ogr_unicode)" contract.

As a result, when we try and bring things from OGR into the server encoding, with a [transcode](https://github.com/pramsey/pgsql-ogr-fdw/blob/d58d2a323efbf511862e4f58bc5078a588f9f9d2/ogr_fdw.c#L1590) now, it fails. If this is taken out, it just means that folks w/ non-UTF database encodings will get screwed a bit. Everyone else should be fine. So, insofar is it's more likely that people are loading data that GDAL doesn't enforce to UTF-8 than it is that people are running not-UTF databases, the change should be reverted.

**Comment by robe2** [comment]
Hard call.  Guess there is no way to do the transcode thing and fail with a warning.

The upside of the current behavior is I'm warned this loaded data is crap (as is often the case from mainframe data) before it goes in my db.  When I was able to bring this in, restores of my database would fail with the same UTF-8 error without passing it thru a iconv processor (or having a maintenance routine that cleans up the crap characters after they are loaded in the table).

The downside is there isn't much I can do about bad column, because even simply not selecting the offending column still fails and I wouldn't be able to read the bad data to fix it.

**Comment by pramsey** [comment]
Well for some reason the OGR [CSV reader](http://www.gdal.org/drv_csv.html) doesn't have an encoding option, which seems odd for a format (text) that is sure to be produced with different encodings. I guess the user is supposed to just iconv it. Speaking of which you could just `iconv -f WINDOWS-1252 -t UTF-8` your file before loading it?

**Comment by robe2** [comment]
Yah that works.  Okay let's leave this as a won't fix then.  If it weren't a regression I wouldn't have even cared.

**Comment by pramsey** [comment]
I see there's actually a driver capability test in OGR, `OLCStringsAsUTF8`, so I can probably just make the behaviour conditional on OGR attesting to a UTF-8 contract.

**Comment by robe2** [comment]
ah great.  Let me know when you have it and I'll test it out.

**Comment by robe2** [comment]
Just tested looks good.  Thanks.
