### ISSUE TITLE
gdal-config command not found (Windows)

### ISSUE THREAD

**Issue by ofelix03** [pramsey/pgsql-ogr-fdw#149]
Hi there, 

I've install the GDAL core and the binding for python2.7. But I still get gdal-config command not found when I try to build  'qgsql-ogr-fdw' on windows with the make command
![gdal error](https://user-images.githubusercontent.com/9988430/36097226-e929aa7a-0ff1-11e8-97f1-52827975f59a.PNG)

Any help would be well appreciated.

**Comment by pramsey** [comment]
You don't say _how_ you install gdal, but if it's packages you'll need gdal-dev also.

**Comment by ofelix03** [comment]
Thank you @pramsey for the quick response. Indeed I hadn't installed gdal-dev. Installing it got me the gdal-config utility. Successfully installed ogr_fdw

Next issue is, I'm not able to find the  **ogr_fdw_info** utility as cited in your README. Does it require another package to be installed or what?

Running which **ogr_fdw_info** returns nothing.

Thanks again.

**Comment by pramsey** [comment]
You probably haven't run 'make' yet. Is there someone in your office who can help?
