### ISSUE TITLE
'ogr_fdw_info' -s  /tmp/test not working

### ISSUE THREAD

**Issue by ofelix03** [pramsey/pgsql-ogr-fdw#150]
Hi @pramsey, trying to to connect to the pt_two.shp  data file as suggested in the README directive throws an error. 
I'm being told to run a  commnad with **--config SHAPE_RESTORE_SHX true** to resolve the issue, but am not sure on what binary I should be attaching this flag.

This is the error thrown when I run **ogr_fdw_info -s "/c/Users/felix/Desktop/test"**
***
ERROR 4: Unable to open C:/Users/felix/Desktop/test\pt_two.shx or C:/Users/felix/Desktop/test\pt_two.SHX.Try --config SHAPE_RESTORE_SHX true to restore or create it
ERROR 4: Failed to open file C:/Users/felix/Desktop/test\pt_two.shp.It may be corrupt or read-only file accessed in update mode.
Layers:
***

I hope you have some familiarity with this error. I really need the help. 
I'm using Git Bash on a Windows machine. 

Thanks.

**Comment by ofelix03** [comment]
Hi @pramsey, I got  this issue resolved. I had to setup an ODBC connection to my MS Access DB (.md file) under the  ODBC  **USER DSN** configuration in Windows.


But now I'm facing another  issue when I try to create the server in my pgAdmin or psql session using the  SQL code returned by running:  **ogr_fdw_info -s "ODBC:attendance" -l USERINFO**. 

![1](https://user-images.githubusercontent.com/9988430/36260424-557bba38-1259-11e8-90ea-416dc505c19e.JPG) 

I'm having an issue with connecting through ODBC to the DSN I've setup to the ACCESS DB.

Running this SQL query:
![2](https://user-images.githubusercontent.com/9988430/36260373-263a72be-1259-11e8-953a-f6ac20be852c.JPG)


Thanks

**Comment by pramsey** [comment]
Felix, I'm sorry I cannot do end-user support on github tickets, I use them just for tracking actual verified bugs or enhancement requests. Can you take your query to gis.stackoverflow.com instead? Your odds of getting free help there are much higher.
