### ISSUE TITLE
PG11: No rule to make target 'stringbuffer_pg.bc', needed by 'all'

### ISSUE THREAD

**Issue by ChristophBerg** [pramsey/pgsql-ogr-fdw#153]
pgsql-ogr-fdw fails to build with PG 11beta1 when JIT is enabled, i.e. PostgreSQL was configured --with-llvm:
```
09:13:29 /usr/include/gdal/cpl_config.h:284:9: warning: 'PACKAGE_VERSION' macro redefined [-Wmacro-redefined]
09:13:29 #define PACKAGE_VERSION ""
09:13:29         ^
09:13:29 /usr/include/postgresql/11/server/pg_config.h:788:9: note: previous definition is here
09:13:29 #define PACKAGE_VERSION "11beta1"
09:13:29         ^
09:13:29 5 warnings generated.
09:13:29 /usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I/usr/include/gdal -I. -I/<<PKGBUILDDIR>> -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -flto=thin -emit-llvm -c -o ogr_fdw_common.bc /<<PKGBUILDDIR>>/ogr_fdw_common.c
09:13:30 make[2]: *** No rule to make target 'stringbuffer_pg.bc', needed by 'all'.  Stop.
```
The reason it is failing is because of this Makefile rule, which builds `pg_stringbuffer_pg.o` from `pg_stringbuffer.c` - note the missing `_pg` part:
```
OBJS = ogr_fdw.o ogr_fdw_deparse.o ogr_fdw_common.o stringbuffer_pg.o

stringbuffer_pg.o: stringbuffer.c stringbuffer.h
        $(CC) $(CFLAGS) -D USE_PG_MEM -c -o $@ $<
```
This might as well be a PGXS bug - I'll open a thread on pgsql-hacker for discussion: https://www.postgresql.org/message-id/20180528074432.GB22299%40msg.df7cb.de

**Comment by devrimgunduz** [comment]
I'm also getting these on my Fedora 28 box (gcc 8.1.1)
   
` /usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I/usr/include/gdal -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o ogr_fdw_deparse.bc ogr_fdw_deparse.c
/usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I/usr/include/gdal -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o ogr_fdw_common.bc ogr_fdw_common.c
make[1]: *** No rule to make target 'stringbuffer_pg.bc', needed by 'all'.  Stop.
make[1]: *** Waiting for unfinished jobs....
stringbuffer.c: In function 'stringbuffer_avprintf':
stringbuffer.c:220:2: warning: function 'stringbuffer_avprintf' might be a candidate for 'gnu_printf' format attribute [-Wsuggest-attribute=format]
  len = vsnprintf(s->str_end, maxlen, fmt, ap2);
  ^~~
stringbuffer.c:240:3: warning: function 'stringbuffer_avprintf' might be a candidate for 'gnu_printf' format attribute [-Wsuggest-attribute=format]
   len = vsnprintf(s->str_end, maxlen, fmt, ap);
   ^~~
ogr_fdw_deparse.c: In function 'ogrDeparseNullTest':
ogr_fdw_deparse.c:490:5: warning: this 'else' clause does not guard... [-Wmisleading-indentation]
     else
     ^~~~
ogr_fdw_deparse.c:493:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'else'
  return true;
  ^~~~~~
ogr_fdw.c: In function 'ogrReadColumnData':
ogr_fdw.c:1128:33: error: incompatible types when initializing type 'Form_pg_attribute' {aka 'struct FormData_pg_attribute *'} using type 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'}
   Form_pg_attribute att_tuple = tupdesc->attrs[i];
                                 ^~~~~~~
ogr_fdw.c:1146:16: warning: implicit declaration of function 'get_relid_attribute_name'; did you mean 'get_rte_attribute_name'? [-Wimplicit-function-declaration]
   col.pgname = get_relid_attribute_name(rel->rd_id, att_tuple->attnum);
                ^~~~~~~~~~~~~~~~~~~~~~~~
                get_rte_attribute_name
ogr_fdw.c:1146:14: warning: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
   col.pgname = get_relid_attribute_name(rel->rd_id, att_tuple->attnum);
              ^
ogr_fdw.c: In function 'ogrGetFidColumn':
ogr_fdw.c:2093:34: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
   NameData attname = td->attrs[i]->attname;
                                  ^~
ogr_fdw.c:2094:31: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
   Oid atttypeid = td->attrs[i]->atttypid;
                               ^~
ogr_fdw.c: In function 'ogrAddForeignUpdateTargets':
ogr_fdw.c:2129:6: error: incompatible types when assigning to type 'Form_pg_attribute' {aka 'struct FormData_pg_attribute *'} from type 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'}
  att = tupdesc->attrs[fid_column];
      ^
ogr_fdw.c: In function 'ogrExecForeignUpdate':
ogr_fdw.c:2212:34: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
  fid_type = td->attrs[fid_column]->atttypid;
                                  ^~
ogr_fdw.c: In function 'ogrExecForeignDelete':
ogr_fdw.c:2411:34: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
  fid_type = td->attrs[fid_column]->atttypid;
                                  ^~
make[1]: *** [<builtin>: ogr_fdw.o] Error 1
ogr_fdw.c:1128:21: error: initializing 'Form_pg_attribute' (aka 'struct FormData_pg_attribute *') with an expression of incompatible type 'FormData_pg_attribute' (aka 'struct FormData_pg_attribute'); take the address with &
                Form_pg_attribute att_tuple = tupdesc->attrs[i];
                                  ^           ~~~~~~~~~~~~~~~~~
                                              &
ogr_fdw.c:1146:16: warning: implicit declaration of function 'get_relid_attribute_name' is invalid in C99 [-Wimplicit-function-declaration]
                col.pgname = get_relid_attribute_name(rel->rd_id, att_tuple->attnum);
                             ^
ogr_fdw.c:2093:34: error: member reference type 'FormData_pg_attribute' (aka 'struct FormData_pg_attribute') is not a pointer; did you mean to use '.'?
                NameData attname = td->attrs[i]->attname;
                                   ~~~~~~~~~~~~^~
                                               .
ogr_fdw.c:2094:31: error: member reference type 'FormData_pg_attribute' (aka 'struct FormData_pg_attribute') is not a pointer; did you mean to use '.'?
                Oid atttypeid = td->attrs[i]->atttypid;
                                ~~~~~~~~~~~~^~
                                            .
ogr_fdw.c:2129:6: error: assigning to 'Form_pg_attribute' (aka 'struct FormData_pg_attribute *') from incompatible type 'FormData_pg_attribute' (aka 'struct FormData_pg_attribute'); take the address with &
        att = tupdesc->attrs[fid_column];
            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~
              &
ogr_fdw.c:2212:34: error: member reference type 'FormData_pg_attribute' (aka 'struct FormData_pg_attribute') is not a pointer; did you mean to use '.'?
        fid_type = td->attrs[fid_column]->atttypid;
                   ~~~~~~~~~~~~~~~~~~~~~^~
                                        .
ogr_fdw.c:2411:34: error: member reference type 'FormData_pg_attribute' (aka 'struct FormData_pg_attribute') is not a pointer; did you mean to use '.'?
        fid_type = td->attrs[fid_column]->atttypid;
                   ~~~~~~~~~~~~~~~~~~~~~^~
                                        .
1 warning and 6 errors generated.
make[1]: *** [/usr/pgsql-11/lib/pgxs/src/makefiles/../../src/Makefile.global:1009: ogr_fdw.bc] Error 1
  `

Regards, Devrim

**Comment by devrimgunduz** [comment]
> /usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I/usr/include/gdal -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o ogr_fdw_deparse.bc ogr_fdw_deparse.c
/usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I/usr/include/gdal -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o ogr_fdw_common.bc ogr_fdw_common.c
make[1]: *** No rule to make target 'stringbuffer_pg.bc', needed by 'all'.  Stop.
make[1]: *** Waiting for unfinished jobs....
stringbuffer.c: In function 'stringbuffer_avprintf':
stringbuffer.c:220:2: warning: function 'stringbuffer_avprintf' might be a candidate for 'gnu_printf' format attribute [-Wsuggest-attribute=format]
  len = vsnprintf(s->str_end, maxlen, fmt, ap2);
  ^~~
stringbuffer.c:240:3: warning: function 'stringbuffer_avprintf' might be a candidate for 'gnu_printf' format attribute [-Wsuggest-attribute=format]
   len = vsnprintf(s->str_end, maxlen, fmt, ap);
   ^~~
ogr_fdw_deparse.c: In function 'ogrDeparseNullTest':
ogr_fdw_deparse.c:490:5: warning: this 'else' clause does not guard... [-Wmisleading-indentation]
     else
     ^~~~
ogr_fdw_deparse.c:493:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'else'
  return true;
  ^~~~~~
ogr_fdw.c: In function 'ogrReadColumnData':
ogr_fdw.c:1128:33: error: incompatible types when initializing type 'Form_pg_attribute' {aka 'struct FormData_pg_attribute *'} using type 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'}
   Form_pg_attribute att_tuple = tupdesc->attrs[i];
                                 ^~~~~~~
ogr_fdw.c:1146:16: warning: implicit declaration of function 'get_relid_attribute_name'; did you mean 'get_rte_attribute_name'? [-Wimplicit-function-declaration]
   col.pgname = get_relid_attribute_name(rel->rd_id, att_tuple->attnum);
                ^~~~~~~~~~~~~~~~~~~~~~~~
                get_rte_attribute_name
ogr_fdw.c:1146:14: warning: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
   col.pgname = get_relid_attribute_name(rel->rd_id, att_tuple->attnum);
              ^
ogr_fdw.c: In function 'ogrGetFidColumn':
ogr_fdw.c:2093:34: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
   NameData attname = td->attrs[i]->attname;
                                  ^~
ogr_fdw.c:2094:31: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
   Oid atttypeid = td->attrs[i]->atttypid;
                               ^~
ogr_fdw.c: In function 'ogrAddForeignUpdateTargets':
ogr_fdw.c:2129:6: error: incompatible types when assigning to type 'Form_pg_attribute' {aka 'struct FormData_pg_attribute *'} from type 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'}
  att = tupdesc->attrs[fid_column];
      ^
ogr_fdw.c: In function 'ogrExecForeignUpdate':
ogr_fdw.c:2212:34: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
  fid_type = td->attrs[fid_column]->atttypid;
                                  ^~
ogr_fdw.c: In function 'ogrExecForeignDelete':
ogr_fdw.c:2411:34: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
  fid_type = td->attrs[fid_column]->atttypid;
                                  ^~
make[1]: *** [<builtin>: ogr_fdw.o] Error 1
ogr_fdw.c:1128:21: error: initializing 'Form_pg_attribute' (aka 'struct FormData_pg_attribute *') with an expression of incompatible type 'FormData_pg_attribute' (aka 'struct FormData_pg_attribute'); take the address with &
                Form_pg_attribute att_tuple = tupdesc->attrs[i];
                                  ^           ~~~~~~~~~~~~~~~~~
                                              &
ogr_fdw.c:1146:16: warning: implicit declaration of function 'get_relid_attribute_name' is invalid in C99 [-Wimplicit-function-declaration]
                col.pgname = get_relid_attribute_name(rel->rd_id, att_tuple->attnum);
                             ^
ogr_fdw.c:2093:34: error: member reference type 'FormData_pg_attribute' (aka 'struct FormData_pg_attribute') is not a pointer; did you mean to use '.'?
                NameData attname = td->attrs[i]->attname;
                                   ~~~~~~~~~~~~^~
                                               .
ogr_fdw.c:2094:31: error: member reference type 'FormData_pg_attribute' (aka 'struct FormData_pg_attribute') is not a pointer; did you mean to use '.'?
                Oid atttypeid = td->attrs[i]->atttypid;
                                ~~~~~~~~~~~~^~
                                            .
ogr_fdw.c:2129:6: error: assigning to 'Form_pg_attribute' (aka 'struct FormData_pg_attribute *') from incompatible type 'FormData_pg_attribute' (aka 'struct FormData_pg_attribute'); take the address with &
        att = tupdesc->attrs[fid_column];
            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~
              &
ogr_fdw.c:2212:34: error: member reference type 'FormData_pg_attribute' (aka 'struct FormData_pg_attribute') is not a pointer; did you mean to use '.'?
        fid_type = td->attrs[fid_column]->atttypid;
                   ~~~~~~~~~~~~~~~~~~~~~^~
                                        .
ogr_fdw.c:2411:34: error: member reference type 'FormData_pg_attribute' (aka 'struct FormData_pg_attribute') is not a pointer; did you mean to use '.'?
        fid_type = td->attrs[fid_column]->atttypid;
                   ~~~~~~~~~~~~~~~~~~~~~^~
                                        .
1 warning and 6 errors generated.
make[1]: *** [/usr/pgsql-11/lib/pgxs/src/makefiles/../../src/Makefile.global:1009: ogr_fdw.bc] Error 1
