### ISSUE TITLE
1.0.5 build error on RHEL 6

### ISSUE THREAD

**Issue by devrimgunduz** [pramsey/pgsql-ogr-fdw#155]
Hi,

I'm getting this while building 1.0.5 on RHEL 6. (gcc 4.4.7). Can you please  take a look?

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC -I/usr/include/gdal -I. -I./ -I/usr/pgsql-10/include/server -I/usr/pgsql-10/include/internal -I/usr/include -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o ogr_fdw_common.o ogr_fdw_common.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC -D USE_PG_MEM -c -o stringbuffer_pg.o stringbuffer.c
stringbuffer.c: In function 'stringbuffer_avprintf':
stringbuffer.c:220: warning: function might be possible candidate for 'gnu_printf' format attribute
stringbuffer.c:220: warning: function might be possible candidate for 'gnu_printf' format attribute
stringbuffer.c:240: warning: function might be possible candidate for 'gnu_printf' format attribute
stringbuffer.c:240: warning: function might be possible candidate for 'gnu_printf' format attribute
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC -I/usr/include/gdal -I. -I./ -I/usr/pgsql-10/include/server -I/usr/pgsql-10/include/internal -I/usr/include -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o ogr_fdw_info.o ogr_fdw_info.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC -I/usr/include/gdal -I. -I./ -I/usr/pgsql-10/include/server -I/usr/pgsql-10/include/internal -I/usr/include -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o stringbuffer.o stringbuffer.c
stringbuffer.c: In function 'stringbuffer_avprintf':
stringbuffer.c:220: warning: function might be possible candidate for 'gnu_printf' format attribute
stringbuffer.c:220: warning: function might be possible candidate for 'gnu_printf' format attribute
stringbuffer.c:240: warning: function might be possible candidate for 'gnu_printf' format attribute
stringbuffer.c:240: warning: function might be possible candidate for 'gnu_printf' format attribute
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC -o ogr_fdw_info ogr_fdw_info.o ogr_fdw_common.o stringbuffer.o -L/usr/lib64 -lgdal
ogr_fdw.c:1102:45: error: missing binary operator before token "("
ogr_fdw.c:1445:45: error: missing binary operator before token "("
ogr_fdw.c:1549:45: error: missing binary operator before token "("
ogr_fdw.c:1800:45: error: missing binary operator before token "("
ogr_fdw.c:1821:45: error: missing binary operator before token "("
make[1]: *** [ogr_fdw.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/pgsql/rpm10/BUILD/pgsql-ogr-fdw-1.0.5'
error: Bad exit status from /var/tmp/rpm-tmp.axQnLW (%build)

**Comment by pramsey** [comment]
This seems to be an odd issue with particular versions of the gcc preprocessor, and it only is showing up in if/else/endif blocks, the same pattern in if/endif blocks works fine. Very confusing. I've tried some random bracket-adding, but if you have any guesses about what syntacical tweak make it go, I'd love to know. 

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=36453

**Comment by pramsey** [comment]
Well, I fired up a Centos box with gcc 4.4.7 on it, and I *do not* see this problem against master. The problem seems tied to GDAL_COMPUTE_VERSION() showing up in an #if/#else block, so maybe it's something to do with the macro in a particular version? I tested GDAL 2.2.4.

**Comment by devrimgunduz** [comment]
Hi @pramsey ,

I  am using the latest released version to build the RPMs, this is what we do. If you think that the git master fixes it, can you please do a new release? :)

Cheers, Devrim

**Comment by pramsey** [comment]
Well, I'm not at all sure this will fix it, since I couldn't replicate it, but this has a few changes needed for PgSQL 11 in any event https://github.com/pramsey/pgsql-ogr-fdw/releases/tag/v1.0.6
