### ISSUE TITLE
Possible Parallel cache bug.

### ISSUE THREAD

**Issue by bowguy** [pramsey/pgsql-ogr-fdw#157]
I have been doing some work with ogr_fdw extension.  The extension has worked perfectly for my needs.  However last week I ran into an error message regarding an invalid cache id on a parallel worker.  The reason I bring it up here is the behaviour is identical to the bug described here:
https://www.postgresql.org/message-id/11960.1511116873%40sss.pgh.pa.us
 which states the bug is with oracle_fdw. The difference for me is the cache id is 11 not 41.
Of course today I can't seem to recreate the bug but will keep testing.  The only extensions are postgis and ogr_fdw.
Configuration:
Windows 10
version() = PostgreSQL 10.4, compiled by Visual C++ build 1800, 64-bit
postgis_full_version() = POSTGIS="2.4.4 r16526" PGSQL="100" GEOS="3.6.2-CAPI-1.10.2 4d2925d" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.2.4, released 2018/03/19" LIBXML="2.7.8" LIBJSON="0.12" LIBPROTOBUF="1.2.1" RASTER
Thanks

**Comment by pramsey** [comment]
Thanks for this. I imagine w/ parallel workers reproducing will be hard, but do see what you can do. I'll read up on the email and see if I can figure a fix on that basis alone.

**Comment by pramsey** [comment]
Ah, I see we already have a fix for this at 2d6aa7a42b94cc6b3f541fb8835ee85c7091450b. So this just waits on a release.

**Comment by pramsey** [comment]
Release is available https://github.com/pramsey/pgsql-ogr-fdw/releases/tag/v1.0.7

**Comment by bowguy** [comment]
Perfect!
Did this make it into PostGIS 2.5.0 ?  If so I will just run with that.
Thanks

**Comment by pramsey** [comment]
It's not a postgis bug, it's a ogr_fdw bug.

**Comment by bowguy** [comment]
Understand but the Windows binaries compiled by Regina include ogr_fdw.

**Comment by pramsey** [comment]
I stamped this release 5 minutes ago, and Regina only builds stamped versions, so no, it won't be in the 2.5.0 build.

**Comment by bowguy** [comment]
OK - Thanks!

**Comment by robe2** [comment]
I haven't built 2.5.0 bundle yet.  So YES it will be in the 2.5.0.

I'll also try to build the ogr_fdw binaries later today for those who want to get it before I package the windows 2.5.0 bundles.

**Comment by bowguy** [comment]
Just installed now.  Working perfectly so far.  Thanks!
