### ISSUE TITLE
ogr_fdw_info --formats option would be nice

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#16]
If it's not too much trouble, can we have a --formats or -f or whatever you want to call it option to ogr_fdw_info similar to what ogrinfo has?

**Comment by pramsey** [comment]
Hey @rouault where in the OGR code base does this happen? I'll either call into it directly or copy it.

**Comment by rouault** [comment]
GDAL 2.0 way : https://github.com/OSGeo/gdal/blob/trunk/gdal/gcore/gdal_misc.cpp#L2620
GDAL 1.11 way: https://github.com/OSGeo/gdal/blob/1.11/gdal/ogr/ogrutils.cpp#L702

**Comment by pramsey** [comment]
It's a `-f` option for now, as I haven't flipped the options parser to a longopt form yet, but it's there at 3bbfdd8

**Comment by pramsey** [comment]
And, belatedly, thanks @rouault for the pointer, I spent a decent chunk of time yesterday not finding those :)
