### ISSUE TITLE
Doesn't compile against PostgreSQL 12 head

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#160]
> In file included from ogr_fdw.c:37:
ogr_fdw.h:40:10: fatal error: nodes/relation.h: No such file or directory
 #include "nodes/relation.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: ogr_fdw.o] Error 1

**Comment by robe2** [comment]
I found the commit that broke this:

https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=fa2cf164aaf91e074be653c28e035f65d80eb666

`Rename nodes/relation.h to nodes/pathnodes.h.

The old name of this file was never a very good indication of what it
was for.  Now that there's also access/relation.h, we have a potential
confusion hazard as well, so let's rename it to something more apropos.
Per discussion, "pathnodes.h" is reasonable, since a good fraction of
the file is Path node definitions.

While at it, tweak a couple of other headers that were gratuitously
importing relation.h into modules that don't need it.

Discussion: https://postgr.es/m/7719.1548688728@sss.pgh.pa.us`


I'll submit a patch later after I patch and test

**Comment by robe2** [comment]
Bah evidentally more than that standing in the way:

> In file included from ogr_fdw.c:37:
ogr_fdw.h:50:10: fatal error: optimizer/var.h: No such file or directory
 #include "optimizer/var.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: ogr_fdw.o] Error 1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2  -I/projects/gdal/rel-2.4.0w64gcc81/include -I. -I./ -IC:/MING64~1/projects/POSTGR~1/rel/PG12W6~1/include/server -IC:/MING64~1/projects/POSTGR~1/rel/PG12W6~1/include/internal  -I/projects/zlib/rel-zlib-1.2.11w64gcc81/include  -I/projects/libxml/rel-libxml2-2.7.8w64gcc81/include -I./src/include/port/win32 -DEXEC_BACKEND -I/projects/libxml/rel-libxml2-2.7.8w64gcc81/include/libxml2  -IC:/MING64~1/projects/POSTGR~1/rel/PG12W6~1/include/server/port/win32  -c -o ogr_fdw.o ogr_fdw.c
In file included from ogr_fdw.c:37:
ogr_fdw.h:50:10: fatal error: optimizer/var.h: No such file or directory
 #include "optimizer/var.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: ogr_fdw.o] Error 1

**Comment by robe2** [comment]
Okay got to compile after replacing optimizer/var.h with optimizer/optimizer.h

and taking out T_ArrayRef (what is that for exactly) in ogr_fdw_deparse.c.  I'm trying to find the replacement for it the debugger gave this, but I haven't tried replacing that with T_ParamRef and not sure how to test if it works or not

> ogr_fdw_deparse.c: In function 'ogrDeparseExpr':
ogr_fdw_deparse.c:524:8: error: 'T_ArrayRef' undeclared (first use in this function); did you mean 'T_ParamRef'?
   case T_ArrayRef:
        ^~~~~~~~~~
        T_ParamRef
ogr_fdw_deparse.c:524:8: note: each undeclared identifier is reported only once for each function it appears in
make: *** [<builtin>: ogr_fdw_deparse.o] Error 1
C:/MING64~1/projects/POSTGR~1/rel/PG12W6~1/lib/pgxs/src/MAKEFI~1/../../src/test/regress/pg_regress --inputdir=./ --bindir='C:/MING64~1/projects/POSTGR~1/rel/PG12W6~1/bin'    --encoding=UTF8 --dbname=contrib_regression file pgsql import


I also suspect you don't need optimizer/cost.h as I noticed @adunstan took it out of his file text array fdw
 at https://github.com/adunstan/file_text_array_fdw/commit/dd005ac0d9a3ff2305292e49653bf06b73df8ba2

**Comment by pramsey** [comment]
I have committed a clean build, but regression fails. There's something more deeply changed in the FDW code I think, as I'm seeing a bunch of zeroed out data coming through the slot handler when it should have data.
