### ISSUE TITLE
hstore from osm tags

### ISSUE THREAD

**Issue by nextstopsun** [pramsey/pgsql-ogr-fdw#162]
Is it possible to get all tags from osm driver as hstore column?

**Comment by pramsey** [comment]
I don't think so, the OGR data model doesn't really have a "map" or "dict" type. Best case would be an array of varchar via the OFTStringList OGR type.

**Comment by pramsey** [comment]
So, reading through the osm driver, it looks like this might work almost out of the box if, when you create your target table, you just set the type of the 'other_tags' column to hstore youself. OGR is populating that string column in an hstore-compatible format, and the fdw should just copy it across, so it hits the table definition and gets parsed.

**Comment by pramsey** [comment]
Yeah, no, this is actually quite fiddly. I mapped a osm file into a table with an hstore column for the other_tags column, but the FDW is careful about type mapping.
```
psql: ERROR:  column "other_tags" of foreign table "lines" converts OGR "String" to "hstore"
```
And making it less careful or aware of the hstore type involves quite a bit of gymnastics that I'm not willing to do for one type. You can map other_tags into a varchar column in your FDW table, and then select that column out and cast it straight to hstore in the database, as the format is hstore text form:
```
select other_tags::hstore from lines limit 1;
```
