### ISSUE TITLE
OSX binary distribution of ogr_fdw

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#170]
I'm not sure how to word this since I don't have a Mac.

But I notice OSGeo bottle carries ogr_fdw in binary form as well:

https://bottle.download.osgeo.org/

> 
> osgeo-pgsql-ogr-fdw-1.0.7.high_sierra.bottle.ta..> | 228K | 2019-Apr-03 02:43
> -- | -- | --
> osgeo-pgsql-ogr-fdw-1.0.7.mojave.bottle.tar.gz | 228K | 2019-Apr-03 02:43
> osgeo-pgsql-ogr-fdw-1.0.7.sierra.bottle.tar.gz | 228K | 2019-Apr-03 02:43
> osgeo-pgsql-ogr-fdw-1.0.8.high_sierra.bottle.1...> | 229K | 2019-May-21 15:36
> osgeo-pgsql-ogr-fdw-1.0.8.mojave.bottle.1.tar.gz | 229K | 2019-May-21 15:36
> osgeo-pgsql-ogr-fdw-1.0.8.sierra.bottle.1.tar.gz
> 

It's my understanding people install these via Home Brew and bottle is some sort of binary format if you don't want to run homebrew scripts to build your own.

**Comment by pramsey** [comment]
Are you suggesting I get into the packaging business?

**Comment by robe2** [comment]
No of course not.  Just saying if there is a package you should mention it.  Of course I can't test cause I don't have a Mac.  Mac is the only system I think at this point I can't test.

**Comment by kristfal** [comment]
To help those on Mac OS who may have issues installing this (feel free to add to readme):

1) Remove all previously installed instances of `postgres`, `postgis`, `gdal` and derived dependencies using `brew uninstall postgis gdal` and remove the linked dependencies as well 
2) `brew tap osgeo/osgeo4mac`
3) `brew install osgeo/osgeo4mac/osgeo-pgsql-ogr-fdw`
4) Work around the version issues by within osgeo by:

```
brew uninstall osgeo-gdal osgeo-proj osgeo-libspatialite osgeo-gdal-python --ignore-dependencies &&
brew install https://raw.githubusercontent.com/OSGeo/homebrew-osgeo4mac/b37f82142e347c293cf0b7992f6187d40116b2ca/Formula/osgeo-proj.rb &6
brew install https://raw.githubusercontent.com/OSGeo/homebrew-osgeo4mac/27f4ac2bc4056750307cee1b7a6abb9e33c846dd/Formula/osgeo-libspatialite.rb &&
brew install https://raw.githubusercontent.com/OSGeo/homebrew-osgeo4mac/de5db18027bc37cd3bb0d4be07f59fdc8fe55df9/Formula/osgeo-gdal-python.rb &&
brew install https://raw.githubusercontent.com/OSGeo/homebrew-osgeo4mac/f53c0e8ab8b9acce4fdc5956b508b6ded456ab5b/Formula/osgeo-gdal.rb
```

**Comment by robe2** [comment]
@kristfal  I think these instructions might need a dedicated page.  

@pramsey  What diya think - Perhaps a dedicated MacOS page linked off from the main README?

**Comment by pramsey** [comment]
Ew. Wouldn't fixing the HomeBrew be a better thing to do?

**Comment by robe2** [comment]
> 
> 
> Ew. Wouldn't fixing the HomeBrew be a better thing to do?

How doable is that?  If its doable well of course that is a better solution.  I just thought such alternatives were not an option.

**Comment by salahelfarissi** [comment]
Hi
I'm looking into how to install on Mac.
Is there a solution for how to do that.
