### ISSUE TITLE
1.0.9?

### ISSUE THREAD

**Issue by devrimgunduz** [pramsey/pgsql-ogr-fdw#174]
Hi,

I saw 1.0.9 on PGXN. Will you also release in here? I don't want to change the URLs in the spec file :)

Cheers, Devrim

**Comment by pramsey** [comment]
OK, numbers are cheap https://github.com/pramsey/pgsql-ogr-fdw/releases/tag/v1.0.9

**Comment by devrimgunduz** [comment]
That was *really* fast. Thanks Paul :)
