### ISSUE TITLE
please document installation better for devs with other background

### ISSUE THREAD

**Issue by barbalex** [pramsey/pgsql-ogr-fdw#182]
First and foremost: Thanks for this great tool. I would love to use it - it sounds like the perfect match to use wfs services in one of my projects.

The readme says (emphasis and line breaks by me):
> To build the wrapper, make sure you have **the GDAL library** 
> and **development packages** (is gdal-config on your path?) installed, 
> as well as the **PostgreSQL development packages** (is pg_config on your path?)
> **Build the wrapper** with make and make install. Now you are ready to create a foreign table

This is a lot to digest for a Javascript/Node dev like me. Who has never done any of the four things mentioned here.

It would be very helpful if these four steps would be separated clearly and explained better. For instance: 
- what are gdal dev packages (I could find nothing on https://gdal.org - only references to development source) and where can we find up to date information on how to install them?
- Why are PostgreSQL development packages needed and where can we find up to date information on how to install them?
- How is the wrapper built exactly? Example code? Where is the `make` command entered and what software is needed for `make` to work? (maybe python?)
- is there maybe even a docker image that demonstrates the whole process?

I first wanted to add the following point. But I realize it is not helpful so I am just including it seperately so you know how hard such installations can be for Javascript/Node devs:
- As I suspect python is needed somewhere in this installation: What version of python / how to deal with problems arising from different versions maybe having been installed on a machine earlier? This has bitten me and many others rather often when installing tools depending on python. It has bitten me so bad that I shudder every time I read "python" in an installation readme. I have a feeling that the two versions of python share the same global name which makes some tools break every time one of the versions is globally installed (but I may be completely wrong here). There must be a resource in the python world that helps python and non python devs to deal with the pains of this problem that could be linked to.

**Comment by pramsey** [comment]
I'm afraid detailed instructions for folks who don't understand system packaging is a bit beyond the remit of this project. I should perhaps includes some links to the PGDG yum repositories, but that then builds in assumptions like "you're using linux" and even more "you're using the PGDG builds". 

There's just too many potential install paths and starting points (I'm on MacOS with HomeBrew, I'm on MacOS with MacPorts, I'm using Debian with the system postgres, I'm using Ubuntu with the PgDG Postgres, I'm using Centos with whatever Postgres I got in the box, I'm using RHEL8, I'm using RHEL6, I'm using Windows (Ironically, Windows despite being the hardest platform to build on is the easiest one to target with a single build variant.))

Anyways, if you want to build from source: (a) build gdal from source and install (b) build postgresql from source and install and (c) build ogr_fdw from source and install.

* Here's a windows build http://www.postgresonline.com/journal/index.php?/archives/398-PostgreSQL-12-64-bit-for-Windows-FDWs.html#extended

* If you're on debian, maybe try `apt-cache search ogr_fdw`

* If you're on a RHEL variant, maybe try `yum search ogr_fdw` or `dnf search ogr_fdw`

If none of the above makes sense to you, please appreciate that this low-level extension to PostgreSQL might not be something you can easily access.

(There is no python dependency. Yes, installing python dependencies is also a mortal PITA. I have found that `virtualenv` makes it less awful, but it's still frightening and awful, and my development laptop is a shambles of half-broken python variants.)

**Comment by barbalex** [comment]
> if you want to build from source

Can I understand that to mean that building from source is not necessary?

I am looking for the most simple way to use pgsql-ogr-fdw.

> If none of the above makes sense to you, please appreciate that this low-level extension to PostgreSQL might not be something you can easily access

This may well be the case 

I work on Windows (dev) and ubuntu via docker.

Will try the linked windows build.

Is there something like it for ubuntu via docker?

**Comment by pramsey** [comment]
There's no docker build, I'm not sure such a thing would even be possible.

If you're running Windows PgSQL, then hopefully the windows build will be all you need.

There are certainly RPM builds and deb builds out there, but whether they work with your install of PgSQL is another thing entirely. Running a search for ogr_fdw in your package manager of choice and seeing what happens is recommended.

**Comment by robe2** [comment]
FWIW if you are building your dockers using your own Dockerfile, adding the following lines should work:

`RUN apt-get install postgresql-12-ogr-fdw`

Replace the 12 with whatever version of PostgreSQL you are running.  Haven't tested above but should work.
If per chance the above doesn't work, you may need to add the apt.postgresql.org repository something like:

```
RUN wget --quiet -O - https://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | apt-key add -
RUN add-apt-repository "deb https://apt.postgresql.org/pub/repos/apt/ $(lsb_release -s -c)-pgdg main 12"
```

Replace the 12 with whatever version of PostgreSQL you are running. 

Examples of postgis/postgresql docker images that might be useful to you - 
https://github.com/postgis/docker-postgis

I'm actually thinking for these we should package ogr_fdw extension as we've got all dependencies already.  I'll add to the wish list of that.

**Comment by robe2** [comment]
I feel like we can close this out don't you @pramsey  and @barbalex ?

**Comment by barbalex** [comment]
yep and thanks for great help
