### ISSUE TITLE
Doesn't compile against PostgreSQL 13 beta1

### ISSUE THREAD

**Issue by robe-app** [pramsey/pgsql-ogr-fdw#187]
> stringbuffer.c:239:3: warning: function 'stringbuffer_avprintf' might be a candidate for 'ms_printf' format attribute [-Wsuggest-attribute=format]
>    len = vsnprintf(s->str_end, maxlen, fmt, ap);
>    ^~~
> x86_64-w64-mingw32-gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2   -shared -static-libgcc -o ogr_fdw.dll  ogr_fdw.o ogr_fdw_deparse.o ogr_fdw_common.o stringbuffer_pg.o -LE:/jenkins/postgresql/rel/pg13w64gcc81/lib  -L/projects/zlib/rel-zlib-1.2.11w64gcc81/lib -L/projects/libxml/rel-libxml2-2.9.9w64gcc81/lib -Wl,--allow-multiple-definition -Wl,--disable-auto-import  -Wl,--as-needed   -L/projects/gdal/rel-2.4.4w64gcc81/lib -lpostgres -lpgport -lgdal -L/projects/gdal/rel-2.4.4w64gcc81/lib -lgdal -Wl,--export-all-symbols -Wl,--out-implib=libogr_fdw.a
> ogr_fdw.o: In function `ogrReadColumnData':
> E:\jenkins\postgis\ogrfdw\branches\1.0.9/ogr_fdw.c:1296: undefined reference to `heap_open'
> E:\jenkins\postgis\ogrfdw\branches\1.0.9/ogr_fdw.c:1456: undefined reference to `heap_close'
> collect2.exe: error: ld returned 1 exit status
> make: *** [E:/jenkins/postgresql/rel/pg13w64gcc81/lib/pgxs/src/makefiles/../../src/Makefile.shlib:370: ogr_fdw.dll] Error 1

**Comment by robe2** [comment]
hmm looks like oracle_fdw already fixed same issue and looks like the new table_open might have existed since PG 12

https://github.com/laurenz/oracle_fdw/commit/19a9ea163d602bb6ca22b6969aa5db88a1980569

I'll take a stab at patching and also switching 12 to do the same and see if it works with 12.

**Comment by robe2** [comment]
cough cough -- any chance we can have a new point release now that PostgreSQL 13 beta1 is out and many distros are carrying ogr_fdw :).  Selfish reason -  Windows builds for PostgreSQL 13beta1 are out too and pgRouting 3.0 came out, so since I'm in packaging mode anyway, would be nice to have a shiny point release I can count on for all windows PostGIS bundle packages.

**Comment by pramsey** [comment]
https://github.com/pramsey/pgsql-ogr-fdw/releases/tag/v1.0.12
