### ISSUE TITLE
ogr_fdw only works with UTF-8 is this a new requirement

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#20]
Just pulled the latest and I don't recall having this issue before.  Now the installcheck gives:

  CREATE EXTENSION ogr_fdw;
+ ERROR:  OGR FDW only works with UTF-8 databases

This is fine except some people might not have server initialized to UTF-8.  Like my windows dev install, defaults to WIN1252.  Wondering if it would make sense to create the database with template0 and then enforce creation with UTF-8 so that people can test even if their cluster does not have UTF-8 as the default.

**Comment by pramsey** [comment]
Well, it's a requirement if they are using non-ASCII7 character. Until I add transcoding to the extension itself. OGR is using UTF-8 strings internally. If the database is not using the same, then I could return garbage to non-UTF8 databases.

**Comment by robe2** [comment]
That's fine, but can you make the regression tests force UTF-8 by building from template0 instead of template1 or is there no way to do that with the PostgreSQL extension installcheck plumbing.

**Comment by pramsey** [comment]
can you try adding the following line to Makefile after the PG_CONFIG line:

REGRESS_OPTS = --encoding=UTF8

**Comment by pramsey** [comment]
d048f03..c951306 adds this to master, seemed to pass in the magic parameter in my test

**Comment by robe2** [comment]
That works.  Thanks.
