### ISSUE TITLE
Records no longer returned for ODBC

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#21]
Okay I built with your latest commit:  https://github.com/pramsey/pgsql-ogr-fdw/commit/f93a7e084c9eb0ea4050ae406d56e58a7fb7dabe

While this doesn't cause an issue for flat files or WFS services I tested, it seems to have completely broken my SQL Server queries I access via ODBC.

Count always returns 0 and doing any kind of select returns no records.

**Comment by pramsey** [comment]
Hm, something about the OGR ODBC driver I wonder?

**Comment by robe2** [comment]
Is there an easy way for me to debug what's going on here?  I'll try on my MS Access database (which also uses ODBC) to see if it does the same  thing.  Might be something specific to SQL Server.  I guess I can also try the MSSpatial driver (which behind the scenes also using ODBC but doesn't require a System DSN and also does some other stuff (guess it queries it a bit differently) )

**Comment by pramsey** [comment]
If you crank up the debug log level you’ll see some more info being generated, like the SQL being created for the OGR driver (though, for a simple select count(*) there shouldn’t be any SQL generated.

**Comment by robe2** [comment]
I was partly wrong.  It does seem to return answers if I do a WHERE condition that gets pushed down, but any kind of limit or count (without filter) returns no records

If I set the debug level to 1 , I get the below in logs, and 0 is returned for count

```
LOCATION:  AutoVacWorkerMain, src\backend\postmaster\autovacuum.c:1672
DEBUG:  OGR SQL: 
STATEMENT:  SELECT count(*) from sql_svr.information_schema_columns 

```

When I execute this statement:
```
SELECT count(*) from sql_svr.information_schema_columns ;

```

If I run this:

```
SELECT count(*) from sql_svr.information_schema_columns  WHERE column_name = 'recid';

```

It returns 3 like its supposed to and log shows this:

```
DEBUG:  OGR SQL: (column_name = 'recid')

```

```
SELECT * from sql_svr.information_schema_columns  LIMIT 1;

```

Returns no records (in the older version it did correctly return one record and count of whole table returned a valid count

```
LOCATION:  AutoVacWorkerMain, src\backend\postmaster\autovacuum.c:1672
DEBUG:  autovacuum: processing database "contrib_regression"
DEBUG:  OGR SQL: 
STATEMENT:  SELECT * from sql_svr.information_schema_columns  LIMIT 1;

```
Now querying a libreoffice worksheet also show OGR SQL: nothing  for both count, limit but returns the right answers. and shows OGR_SQL if I do something like WHERE amount > 500;

```

**Comment by robe2** [comment]
I should add that if I do:

```
SELECT * from sql_svr.information_schema_columns  WHERE column_name > '' LIMIT 1;

```

then that works.  and the OGR SQL shows:

```
OGR SQL: (column_name > '')

```

So it seems like in the case of SQL Server, if I have any push down logic, my query will work.  But totally bunks out if OGR SQL = ''.  Where as for the flat files it just falls back on the old model if push down can't be done.

**Comment by pramsey** [comment]
That could be the info needed. I’ll try to ensure that, in the case of “no pushdowns” the attribute filter is set to NULL and not set to “”

**Comment by pramsey** [comment]
I wonder if 00d9aa4 helps?

**Comment by robe2** [comment]
Yap that did the trick.  Thanks
