### ISSUE TITLE
Can we have a 1.0.13 release?

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#210]
Really looking  forward to packaging the character encoding support https://github.com/pramsey/pgsql-ogr-fdw/pull/197 provided by @bowguy

**Comment by pramsey** [comment]
It will be 1.1.0, FYI

**Comment by bowguy** [comment]
Paul supplied the fix.  I just whinged a lot and tested.

**Comment by robe2** [comment]
> 
> 
> It will be 1.1.0, FYI
Okay

**Comment by pramsey** [comment]
https://github.com/pramsey/pgsql-ogr-fdw/releases/tag/v1.1.0
