### ISSUE TITLE
A release to go along with PostgreSQL 14 beta2

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#216]
PostgreSQL 14 beta2 just came out and now that we have fixed the issues broken between beta1 and beta2.  Any chance we can have a tagged release so PostgreSQL maintainers can start packaging that with PostgreSQL 14 beta2 :)

**Comment by pramsey** [comment]
https://github.com/pramsey/pgsql-ogr-fdw/releases/tag/v1.1.1
