### ISSUE TITLE
Unexpected empty string as NULL behavior after environment migration.

### ISSUE THREAD

**Issue by irieill** [pramsey/pgsql-ogr-fdw#218]
After migrating my (Windows) environment from

OGR_FDW: 1.0.2
PostgreSQL: 9.3 w64
Built: 20161016
GIT_REPO: https://github.com/pramsey/pgsql-ogr-fdw
GIT_BRANCH: v1.0.2
GIT_REVISION: de8b90e34fc64c334674d640db7bd2ec21cb2412
GDAL_VER: 2.1.1

to at least

OGR_FDW: 1.0.8
PostgreSQL: 9.6 w64
Built: 20190520
GIT_REPO: https://github.com/pramsey/pgsql-ogr-fdw
GIT_BRANCH: 
GIT_REVISION: 
GDAL_VER: 2.2.4

I encounter unexpected behavior on reading SQLServer (2016) in that empty strings are returned as NULL after migration.

On **SQLServer** side I have the following table:
```
CREATE TABLE [dbo].[Test](
	[key] [nvarchar](100) NOT NULL,
	[value] [nvarchar](100) NOT NULL
)
```
On **PostgreSQL** side I have the following foreign server and table:
```
CREATE SERVER sqlserver
    FOREIGN DATA WRAPPER ogr_fdw
    OPTIONS (
        datasource 'MSSQL:Server=localhost\\SQLEXPRESS2016;Database=FooBar;Driver=SQL Server;UID=Foo;PWD=Bar;Tables=dbo.Test'
        , format 'MSSQLSpatial'
    );

CREATE FOREIGN TABLE test(
    key character varying not NULL COLLATE pg_catalog."default",
    value character varying not NULL COLLATE pg_catalog."default"
)
SERVER sqlserver
OPTIONS (layer 'dbo.Test');
```
When selecting data every empty string is reported as NULL. Even more confusing: 
```
select count(*) from test; -- returns 123
select count(*) from test where value is not null; -- returns 89
select count(*) from test where value is null; --returns 0
```
I have searched and reviewed code several hours now and learned that with [GDAL 2.2 something changed](https://gdal.org/development/rfc/rfc67_nullfieldvalues.html) that is maybe related. Since ogw_fdr is my entry point, I opend this issue not knowing if it even is related to ogw_fdr. But I am stuck and appreciate any help.

I also tested having the same problem with

OGR_FDW: 1.1.0
PostgreSQL: 12 w64
Built: 20210608
GIT_REPO: https://github.com/pramsey/pgsql-ogr-fdw
GIT_BRANCH: 
GIT_REVISION: 
GDAL_VER: 3.2.3

**Comment by irieill** [comment]
I replicated the unexpected behavior with a simple file-based CSV-datasource. Especially the explicit empty strings in the last line should not be returned as NULL. Again the counting stuff is weired.
```
A,B,C,D,E
1,2,3,4,5
1,,3,,5
,2,,4,
"","","","",""
```
```
CREATE SERVER test_csv FOREIGN DATA WRAPPER ogr_fdw
OPTIONS (
  datasource 'CSV:C:/Daten/test.csv'
  , format 'CSV'
  , config_options 'CPL_DEBUG=ON'
);
```
```
CREATE FOREIGN TABLE test_csv (
  a varchar,
  b varchar,
  c varchar,
  d varchar,
  e varchar
) SERVER test_csv
OPTIONS (layer 'test');
```
```
select * from test_csv; --4
```
![Screenshot 2021-08-30 075848](https://user-images.githubusercontent.com/21124034/131292410-48885442-5583-4d18-a159-35817450e2d5.png)
```
DEBUG:  GDAL config option 'CPL_DEBUG' set to 'ON'
DEBUG:  GDAL None [0] GDAL: GDALOpen(CSV:C:/Daten/test.csv, this=000000000086D5A0) succeeds as CSV.
DEBUG:  ogrReadColumnData matched 0 FID, 0 GEOM, 5 FIELDS out of 5 PGSQL COLUMNS
DEBUG:  OGR SQL: 
DEBUG:  GDAL None [0] GDAL: GDALClose(CSV:C:/Daten/test.csv, this=000000000086D5A0)
DEBUG:  GDAL config option 'CPL_DEBUG' set to 'ON'
DEBUG:  GDAL None [0] GDAL: GDALOpen(CSV:C:/Daten/test.csv, this=000000000086DC00) succeeds as CSV.
DEBUG:  ogrReadColumnData matched 0 FID, 0 GEOM, 5 FIELDS out of 5 PGSQL COLUMNS
DEBUG:  processed 4 rows from OGR
DEBUG:  GDAL None [0] CSV: 4 features read on layer 'test'.
DEBUG:  GDAL None [0] GDAL: GDALClose(CSV:C:/Daten/test.csv, this=000000000086DC00)
```
```
select count(*) from test_csv where a is not null; --2
```
```
DEBUG:  GDAL config option 'CPL_DEBUG' set to 'ON'
DEBUG:  GDAL None [0] GDAL: GDALOpen(CSV:C:/Daten/test.csv, this=000000000086D6B0) succeeds as CSV.
DEBUG:  ogrReadColumnData matched 0 FID, 0 GEOM, 5 FIELDS out of 5 PGSQL COLUMNS
DEBUG:  OGR SQL: (A IS NOT NULL)
DEBUG:  GDAL None [0] GDAL: GDALClose(CSV:C:/Daten/test.csv, this=000000000086D6B0)
DEBUG:  GDAL config option 'CPL_DEBUG' set to 'ON'
DEBUG:  GDAL None [0] GDAL: GDALOpen(CSV:C:/Daten/test.csv, this=000000000086DC00) succeeds as CSV.
DEBUG:  ogrReadColumnData matched 0 FID, 0 GEOM, 5 FIELDS out of 5 PGSQL COLUMNS
DEBUG:  processed 4 rows from OGR
DEBUG:  GDAL None [0] CSV: 4 features read on layer 'test'.
DEBUG:  GDAL None [0] GDAL: GDALClose(CSV:C:/Daten/test.csv, this=000000000086DC00)
```
```
select count(*) from test_csv where a is null; --0
```
```
DEBUG:  GDAL config option 'CPL_DEBUG' set to 'ON'
DEBUG:  GDAL None [0] GDAL: GDALOpen(CSV:C:/Daten/test.csv, this=000000000086D270) succeeds as CSV.
DEBUG:  ogrReadColumnData matched 0 FID, 0 GEOM, 5 FIELDS out of 5 PGSQL COLUMNS
DEBUG:  OGR SQL: (A IS NULL)
DEBUG:  GDAL None [0] GDAL: GDALClose(CSV:C:/Daten/test.csv, this=000000000086D270)
DEBUG:  GDAL config option 'CPL_DEBUG' set to 'ON'
DEBUG:  GDAL None [0] GDAL: GDALOpen(CSV:C:/Daten/test.csv, this=000000000086DE20) succeeds as CSV.
DEBUG:  ogrReadColumnData matched 0 FID, 0 GEOM, 5 FIELDS out of 5 PGSQL COLUMNS
DEBUG:  processed 0 rows from OGR
DEBUG:  GDAL None [0] CSV: 4 features read on layer 'test'.
DEBUG:  GDAL None [0] GDAL: GDALClose(CSV:C:/Daten/test.csv, this=000000000086DE20)
```
```
select count(*) from test_csv where a != ''; --2
```
```
DEBUG:  GDAL config option 'CPL_DEBUG' set to 'ON'
DEBUG:  GDAL None [0] GDAL: GDALOpen(CSV:C:/Daten/test.csv, this=000000000086DC00) succeeds as CSV.
DEBUG:  ogrReadColumnData matched 0 FID, 0 GEOM, 5 FIELDS out of 5 PGSQL COLUMNS
DEBUG:  OGR SQL: (A <> '')
DEBUG:  GDAL None [0] GDAL: GDALClose(CSV:C:/Daten/test.csv, this=000000000086DC00)
DEBUG:  GDAL config option 'CPL_DEBUG' set to 'ON'
DEBUG:  GDAL None [0] GDAL: GDALOpen(CSV:C:/Daten/test.csv, this=000000000086D050) succeeds as CSV.
DEBUG:  ogrReadColumnData matched 0 FID, 0 GEOM, 5 FIELDS out of 5 PGSQL COLUMNS
DEBUG:  processed 2 rows from OGR
DEBUG:  GDAL None [0] CSV: 4 features read on layer 'test'.
DEBUG:  GDAL None [0] GDAL: GDALClose(CSV:C:/Daten/test.csv, this=000000000086D050)
```
```
select count(*) from test_csv where a = ''; --0
```
```
DEBUG:  GDAL config option 'CPL_DEBUG' set to 'ON'
DEBUG:  GDAL None [0] GDAL: GDALOpen(CSV:C:/Daten/test.csv, this=000000000086DC00) succeeds as CSV.
DEBUG:  ogrReadColumnData matched 0 FID, 0 GEOM, 5 FIELDS out of 5 PGSQL COLUMNS
DEBUG:  OGR SQL: (A = '')
DEBUG:  GDAL None [0] GDAL: GDALClose(CSV:C:/Daten/test.csv, this=000000000086DC00)
DEBUG:  GDAL config option 'CPL_DEBUG' set to 'ON'
DEBUG:  GDAL None [0] GDAL: GDALOpen(CSV:C:/Daten/test.csv, this=000000000086D160) succeeds as CSV.
DEBUG:  ogrReadColumnData matched 0 FID, 0 GEOM, 5 FIELDS out of 5 PGSQL COLUMNS
DEBUG:  processed 2 rows from OGR
DEBUG:  GDAL None [0] CSV: 4 features read on layer 'test'.
DEBUG:  GDAL None [0] GDAL: GDALClose(CSV:C:/Daten/test.csv, this=000000000086D160)
```

**Comment by irieill** [comment]
As I replicated with a file based data source i do not think that it is a driver based issue. From my point of view in both tests the output `DEBUG:  processed % rows from OGR` is perfectly ok with respect to the expected result. So ogr_fdw seems to be working fine, but what reason for the final count/result is not valid? Do you have any ideas where this is originating from? I am not familliar with the technoligy stack between PostgreSql and ogr_fdw. So any adwise where to ask/report would be very helpful.

**Comment by pramsey** [comment]
Thanks for the extra info. I'll check into it, now we have a replicator I can run. I bet there's a mapping from '' into NULL somewhere, but I also bet it's there for a reason for some other driver, so it will have to be handled carefully.

**Comment by pramsey** [comment]
OK, for posterity, I think I see what's going on.

https://github.com/pramsey/pgsql-ogr-fdw/blob/master/ogr_fdw.c#L1907

So, we have a test that's turning empty string into NULL. I'm pretty sure the reason that is there is because we are also handling non-string types in this block, and for formats that don't have the concept of NULL, a NULL number will come through as an empty string. This is a problem when the input is a string... of course, then we end up being unable to represent NULL for strings for some formats, but for those formats... 🤷 

Anyways, pretty sure the fix is to just add in a test that only goes NULL when dealing with non-string inputs.
