### ISSUE TITLE
location & permissions for VRT file?

### ISSUE THREAD

**Issue by Brent-Wood** [pramsey/pgsql-ogr-fdw#224]
I have a Postgres DB with ogr_fdw installed. I can successfully connect to a WFS service, and query the foreign table, and I'm now trying to access an external MySQL database using a VRT file. 

The VRT file is working with QGIS (to retrieve and plot the data) and with ogr_fdw_info, eg:

ogr_fdw_info -s "/home/woodb/fdw/SpecifyQuery3.vrt"
Format: OGR_VRT

Layers:
  collectionObjects

When I try to create the server in the Postgres db I get an error:
CREATE SERVER specify_vrt
   FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (  datasource '/home/woodb/fdw/SpecifyQuery3.vrt',
                      format 'VRT');"
ERROR:  unable to connect to data source "/home/woodb/fdw/SpecifyQuery3.vrt"

I understand the message to mean the VRT file can't be found, rather than the file can be found but the datasource it points at can't. I have tried changing permissions & locations of the file, but have always got this error message.

Any advice on what I'm doing wrong here, and how to make this work?

Thanks.

**Comment by robe2** [comment]
I think this ticket can be closed?
