### ISSUE TITLE
-f flag requires an argument

### ISSUE THREAD

**Issue by arenius** [pramsey/pgsql-ogr-fdw#227]
The documentation states:

> ogr_fdw_info -f
> 
> Supported Formats:
>   -> "PCIDSK" (read/write)
>   -> "netCDF" (read/write)
>   ...
>   -> "HTTP" (readonly)

However, when I run `ogr_fdw_info -f` the output is:

> 
> ogr_fdw_info: option requires an argument -- 'f'
> usage: ogr_fdw_info -s <ogr datasource> -l <ogr layer name> -i <ogr layer index (numeric)> -t <output table name> -n <output server name> -o <config options>
>        ogr_fdw_info -s <ogr datasource>
> usage: ogr_fdw_info -f
>        Show what input file formats are supported.
> 
> note (1): You can specify either -l (layer name) or -i (layer index) if you specify both -l will be used
> note (2): config options are specified as a comma deliminated list without the OGR_<driver>_ prefix
> so OGR_XLSX_HEADERS = FORCE OGR_XLSX_FIELD_TYPES = STRING would become:
> "HEADERS = FORCE,FIELD_TYPES = STRING"

I'm running on Ubuntu 20.04.3 LTS with PostgreSQL 11 from the PostgreSQL repository.  I've tried with a version installed via apt and with a version I've compiled myself.

**Comment by robe2** [comment]
@pramsey  Sounds like you already fixed this. Is there more to do here?
