### ISSUE TITLE
Regression tests don't work on PG15 even after 1.1.3

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#243]
On my ubuntu setup, I get this in file.out

```
CREATE EXTENSION ogr_fdw;
CREATE SERVER myserver
  FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
    datasource '/root/projects/pgsql-ogr-fdw/data',
    format 'ESRI Shapefile' );
ERROR:  unable to connect to data source "/root/projects/pgsql-ogr-fdw/data"
```

Shouldn't there be a file name after the /data/ part

**Comment by robe2** [comment]
okay I'm mistaken that is a folder path.  The path looks right too.  so it's probably the permissioning doesn't work.  I'll confirm and close out.  Weird though doesn't work on my mingw either and that I runs under my account so shouldn't have an issue and has always worked before.

**Comment by pramsey** [comment]
Yeah, it's permissions almost certainly. The postgres process needs access to the location of the data file.

**Comment by robe2** [comment]
Apologies.  Yap permission issue.  Only test that fails is the pgsql one, but that one is also because I'm running against a prodcution installed that doesn't allow no password.

**Comment by robe2** [comment]
Just a note, the tests no longer work for me under mingw64 (postgresql launched with batch script), but that might be the psql change you were alluding to.

So right now I'm getting:
`/sources/pgsql_ogr_fdw/data`

as the path, where as before, I would get

`C:/projects/sources/pgsql_ogr_fdw/data`

But I won't reopen since this might be something on my end I need to change in my chimera setup.
