### ISSUE TITLE
 undefined symbol: GEOSConcaveHull installing from redhat repo

### ISSUE THREAD

**Issue by rinaldsb** [pramsey/pgsql-ogr-fdw#245]
# installed postgresqlfrom  redhat repo
dnf -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
dnf config-manager --set-disabled pgdg10 pgdg11 pgdg12 pgdg13 pgdg15
dnf makecache
dnf install postgresql14 postgresql14-server postgresql14-contrib postgresql14-devel postgis33_14 ogr_fdw_14

# as postgres
mkdir ~/shp
wget https://www.geofabrik.de/data/shapefiles_dresden.zip -O ~/shp/shapefiles_dresden.zip
(cd ~/shp; unzip -q shapefiles_dresden.zip)

createdb impshp

(cat << 'EOF'
CREATE EXTENSION postgis;
CREATE EXTENSION ogr_fdw;
EOF
) | psql impshp

# extensions
for a in $(echo "select datname from pg_database where datname not like 'template%' order by datname;" | psql -tA ) 
do 
echo "#--$a extensions-------------------------------------------------"
echo "select extname,extversion from pg_extension" | psql -t $a  
done

#--impshp extensions---
 plpgsql | 1.0
 postgis | 3.3.2
 ogr_fdw | 1.1
 

echo "SELECT postgis_full_version();"  | psql -tqA impshp
POSTGIS="3.3.2 4975da8" [EXTENSION] PGSQL="140" GEOS="3.11.1-CAPI-1.17.1" PROJ="9.0.1" LIBXML="2.9.7" LIBJSON="0.13.1" LIBPROTOBUF="1.3.0" WAGYU="0.5.0 (Internal)"

(cat << 'EOF'
CREATE SERVER IF NOT EXISTS shapes
  FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
    datasource '/home/postgres/shp'
    ,format 'ESRI Shapefile'
    );
EOF
) | psql impshp  
 
(cat << 'EOF'
IMPORT FOREIGN SCHEMA "ogr_all"
FROM SERVER shapes INTO public;
EOF
) | psql impshp
 
NOTICE:  Number of tables to be created 29
ERROR:  could not load library "/usr/pgsql-14/lib/postgis-3.so": /usr/pgsql-14/lib/postgis-3.so: undefined symbol: GEOSConcaveHull

**Comment by pramsey** [comment]
This is a build issue with the RPMs you have installed. PostGIS appears to have been built against GEOS 3.11, but your system seems to have an older version of GEOS installed. It's also possible, if you're mixing builds from different places that you have an old GEOS floating around your system somewhere that is finding its way in front of GEOS 3.11 in your linker rules. If you have a clean machine with only PGDG RPMs on it, then the PGDG build is currently borked and short be reported there.
