### ISSUE TITLE
Support GDAL/OGR configuration options in CREATE SERVER

### ISSUE THREAD

**Issue by rastermanden** [pramsey/pgsql-ogr-fdw#26]
I am trying to understand the different levels of encoding/recoding in ogr_fdw.

I have a dataset which I can load into my database using regular ogr2ogr :

```bash
export PGCLIENTENCODING=latin1
ogr2ogr -overwrite -f "postgresql" pg:"dbname=opendata" -nln matrikelkort.jordstykke_1084 /vsizip//vsicurl/ftp://testuser_ogr_fdw:testuser_ogr_fdw@ftp.kortforsyningen.dk/matrikeldata/matrikelkort/SHAPE/1084_SHAPE_UTM32-EUREF89.zip/1084_SHAPE_UTM32-EUREF89/MINIMAKS/BASIS/JORDSTYKKE.shp JORDSTYKKE
```
**Note**: The datasource is free and open data from Denmark. I created the user/pass for this issue to make it easier to reproduce. 
You can create your own user/pass [here](http://download.kortforsyningen.dk//content/opret-mig-som-bruger) if you like.

My database is UTF8 and the data looks fine when querying records with latin1 characters:

```sql
SELECT elavsnavn, 
       elavskode, 
       matrnr 
FROM   matrikelkort.jordstykke_1084 
WHERE  elavskode = 2000154 
LIMIT  1 
```

**Returns**

| elavsnavn             | elavskode | matrnr |
|-----------------------|-----------|--------|
| Damhussøen, København | 2000154   | 7000a  |

Which is perfect!

Now that I have tested and confirmed I can load the data correctly with ogr2ogr, I will set up a FOREIGN TABLE like this:

```sql
DROP SERVER IF EXISTS matrikel_jordstykke CASCADE;
CREATE SERVER matrikel_jordstykke
   FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
  datasource '/vsizip//vsicurl/ftp://testuser_ogr_fdw:testuser_ogr_fdw@ftp.kortforsyningen.dk/matrikeldata/matrikelkort/SHAPE/1084_SHAPE_UTM32-EUREF89.zip/1084_SHAPE_UTM32-EUREF89/MINIMAKS/BASIS/JORDSTYKKE.shp',
  format 'ESRI Shapefile');

DROP FOREIGN TABLE IF EXISTS matrikelkort.jordstykke;
CREATE FOREIGN TABLE matrikelkort.jordstykke (
  fid integer,
  geom geometry(POLYGON, 25832),
  uuid character varying,
  feat_id real,
  feat_kode real ,
  feat_type character varying,
  elavsnavn character varying,
  elavskode double precision,
  matrnr character varying,
  kms_sagsid real,
  kms_journr character varying,
  skelsagsid real,
  supmsagsid real,
  komnavn character varying,
  komkode integer,
  sognnavn character varying,
  sognkode integer,
  regionnavn character varying,
  regionkode integer,
  retskrnavn character varying,
  retskrkode integer,
  moderjord real,
  regareal real,
  arealbereg character varying,
  vejareal real,
  vejarealbe character varying,
  vandarealb character varying,
  faelleslod character varying,
  esr_ejdnr real,
  sfe_ejdnr real,
  sfe_sagsid real,
  sfe_dato date,
  sfe_journr character varying,
  sfe_note character varying,
  land_note character varying,
  arealtype character varying,
  dq_index real,
  registdato date,
  geomdato date,
  publidato date)
  SERVER matrikel_jordstykke
  OPTIONS ( layer 'JORDSTYKKE' );
```

Now, I make the same query on the FOREIGN TABLE:

```sql
SELECT elavsnavn, 
       elavskode, 
       matrnr 
FROM   matrikelkort.jordstykke 
WHERE  elavskode = 2000154 
LIMIT  1; 
```

**Returns**

| elavsnavn             | elavskode | matrnr |
|-----------------------|-----------|--------|
|  | 2000154   | 7000a  |

Which is not so good, because the data is missing for the column **elavsnavn**.
I was hoping to get around this issue really quick by changing the client encoding like i I did when loading the data with regular ogr2ogr and rerun the query:

```sql
SET CLIENT_ENCODING TO 'latin1';
```
Which returns an error:

**ERROR:  invalid byte sequence for encoding "UTF8": 0xf8**

I am not exactly sure what is happening anymore.

## My questions are:

1. What is the lifecycle of encoding/recoding using ogr_fdw ?
2. Is it possible to pass in [GDAL configuration](http://trac.osgeo.org/gdal/wiki/ConfigOptions) options to the FOREIGN SERVER? I would like to experiment with disabling recoding on the ogr2ogr side with either: setting
 [SHAPE_ENCODING](http://trac.osgeo.org/gdal/wiki/ConfigOptions#SHAPE_ENCODING) to an empty string "" OR using the [-oo (open option) ](http://www.gdal.org/ogr2ogr.html) **ENCODING** ="" in the [shapefile](http://www.gdal.org/drv_shapefile.html)
  driver to avoid any recoding

**Comment by pramsey** [comment]
The set-up currently is to just “hope OGR does things right”. OGR has an internal UTF-8 encoding, and we also assume that users are using a UTF-8 database encoding (and error out if they are not). That leaves the possibility (which I think you are experiencing) that OGR does not do things right. In the *absence* of you telling OGR that the source data are LATIN1, does it do the right thing?

Probably, since there are so many different OGR/GDAL options I’m going to need a way to pass options to OGR in the CREATE SERVER line.

**Comment by rastermanden** [comment]
Thanks for clarifying things.

>  In the *absence* of you telling OGR that the source data are LATIN1, does it do the right thing?

If I omit exporting PGCLIENTENCODING=latin1 in the terminal, I receive the same error: 
```bash
ogr2ogr -overwrite -f "postgresql" pg:"dbname=opendata" -nln matrikelkort.jordstykke_1084 /vsizip//vsicurl/ftp://testuser_ogr_fdw:testuser_ogr_fdw@ftp.kortforsyningen.dk/matrikeldata/matrikelkort/SHAPE/1084_SHAPE_UTM32-EUREF89.zip/1084_SHAPE_UTM32-EUREF89/MINIMAKS/BASIS/JORDSTYKKE.shp JORDSTYKKE
ERROR 1: INSERT command for new feature failed.
ERROR:  invalid byte sequence for encoding "UTF8": 0xf8
```
I'm not really sure if it is doing the right or the wrong thing but the data is not comming in :)

I think it would be a nice improvement to allow passing in config options in the CREATE SERVER line.

**Comment by rastermanden** [comment]
I can now confirm it is working with the [SHAPE_ENCODING](http://trac.osgeo.org/gdal/wiki/ConfigOptions#SHAPE_ENCODING) config option set to latin1


Set as environment variable:
```bash
export SHAPE_ENCODING=latin1
ogr2ogr -overwrite -f "postgresql" pg:"dbname=opendata" -nln matrikelkort.jordstykke_1084_latin1 /vsizip//vsicurl/ftp://testuser_ogr_fdw:testuser_ogr_fdw@ftp.kortforsyningen.dk/matrikeldata/matrikelkort/SHAPE/1084_SHAPE_UTM32-EUREF89.zip/1084_SHAPE_UTM32-EUREF89/MINIMAKS/BASIS/JORDSTYKKE.shp JORDSTYKKE
```
Os set as command line switch:

```bash
ogr2ogr -overwrite -f "postgresql" pg:"dbname=opendata" -nln matrikelkort.jordstykke_latin_test1 /vsizip//vsicurl/ftp://testuser_ogr_fdw:testuser_ogr_fdw@ftp.kortforsyningen.dk/matrikeldata/matrikelkort/SHAPE/1084_SHAPE_UTM32-EUREF89.zip/1084_SHAPE_UTM32-EUREF89/MINIMAKS/BASIS/JORDSTYKKE.shp JORDSTYKKE --config SHAPE_ENCODING latin1
```

**Comment by rastermanden** [comment]
Another way of handeling this is to  pass  in ogr2ogr **OpenOptions** (instead of gdal config options ) by using a [vrt](http://www.gdal.org/gdal_vrttut.html) file.

>Starting with GDAL 2.0, a OpenOptions subelement can be added to specify the open options to apply when opening the source dataset. It has <OOI> (open option item) subelements which have a "key" attribute and the value as the data of the element.

This way you can create a vrt file like this:

```xml
<OGRVRTDataSource>
    <OGRVRTLayer name="JORDSTYKKE">
        <SrcDataSource>/vsizip//vsicurl/ftp://testuser_ogr_fdw:testuser_ogr_fdw@ftp.kortforsyningen.dk/matrikeldata/matrikelkort/SHAPE/1084_SHAPE_UTM32-EUREF89.zip/1084_SHAPE_UTM32-EUREF89/MINIMAKS/BASIS/JORDSTYKKE.shp</SrcDataSource> 
 	<SrcLayer>JORDSTYKKE</SrcLayer>
        <OpenOptions>
            <OOI key="ENCODING">LATIN1</OOI>
        </OpenOptions>
    </OGRVRTLayer>
</OGRVRTDataSource>
```
Then you can do like this:

```sql
DROP SERVER IF EXISTS matrikel_jordstykke_vrt CASCADE;
CREATE SERVER  matrikel_jordstykke_vrt
   FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
  datasource '/Users/diabolic/jordstykke.vrt',
  format 'VRT');
```

Unfortunately, I can't compile ogr_fdw against gdal 2.0

**Comment by rastermanden** [comment]
According to @rouault s [blog](http://erouault.blogspot.dk/2015/05/gdal-20-driver-metadata.html) almost all GDAL_CONFIG options are available as OpenOptions in GDAL 2.0. 

It would be really cool if OpenOptions were supported in the CREATE SERVER statement.

Then, it is not necessary to have acces to the server and place the [vrt](http://www.gdal.org/gdal_vrttut.html) file (  with an OpenOptions XML element).

**Comment by pramsey** [comment]
So, in terms of syntax are we thinking:
```
CREATE SERVER matrikel_jordstykke
   FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
  datasource '/vsizip//vsicurl/ftp://testuser_ogr_fdw:testuser_ogr_fdw@ftp.kortforsyningen.dk/matrikeldata/matrikelkort/SHAPE/1084_SHAPE_UTM32-EUREF89.zip/1084_SHAPE_UTM32-EUREF89/MINIMAKS/BASIS/JORDSTYKKE.shp',
  format 'ESRI Shapefile',
  open_options 'something',
  config_options 'something'
);
```
I guess I cannot get away from having *both* config and open options, since older GDAL versions will have some requirement for general  GDAL options to be handled differently (I see that `ogr2ogr` sets them before running the driver creation, for example).

**Comment by rastermanden** [comment]
The syntax looks good to me.

Regarding having both **open_options** and **config_options** I also think we should have both. In the case of the [WFS driver](http://www.gdal.org/drv_wfs.html), **config options** like  OGR_WFS_PAGING_ALLOWED are not available (according to the driver documentation page) as **open options**. 

Maybe @rouault can share some info on the plans for **config options** vs **open options**

**Comment by rouault** [comment]
The "plan" is to favour open options in new devs. But existing drivers may be only partially converted to open options and there may be config options forgotten in the code. Regarding paging allowed, with WFS 2.0, it is not necessary to specify it as the driver will automatically pick it up if the server supports it

**Comment by pramsey** [comment]
OK, this is coming along in the "gdal_options" branch, currently support global options, like so:
```
CREATE SERVER myserver_latin1
  FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
    datasource '@abs_srcdir@/data',
    format 'ESRI Shapefile',
    config_options 'SHAPE_ENCODING=LATIN1' );
```
Multiple config options have to be placed into the same string, separated by spaces.

**Comment by pramsey** [comment]
There is now also support for open options, for GDAL 2.0+, 
```
CREATE SERVER myserver_latin1
  FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
    datasource '/tmp/test',
    format 'ESRI Shapefile',
    open_options 'ENCODING=LATIN1' 
    );
```

**Comment by rastermanden** [comment]
This is great. I'll test soon!
