### ISSUE TITLE
No packages in PostgreSQL 17 RHEL Yum repositories

### ISSUE THREAD

**Issue by mkleczek** [pramsey/pgsql-ogr-fdw#262]
ogr_fdw is present in PostgreSQL 16 Yum repos but not in PG 17 repos.

It would be great to have it in the latest versions Yum repos.

**Comment by pramsey** [comment]
Talk to packaging maintainers please :) https://redmine.postgresql.org/projects/pgrpms/issues

**Comment by mkleczek** [comment]
Done :)
https://redmine.postgresql.org/issues/8056
