### ISSUE TITLE
geom is null when creating a materialized view from a wfs foreign table

### ISSUE THREAD

**Issue by thomas-szczurek** [pramsey/pgsql-ogr-fdw#263]
Hello,

I can create a foreign server and associated tables  from a wfs server and everything is working fine and I can read it in psql/pgadmin/qgis.

```sql
CREATE SERVER geoplateforme_ign
    FOREIGN DATA WRAPPER ogr_fdw
    OPTIONS (datasource 'WFS:https://data.geopf.fr/wfs', format 'WFS');
```

And table, eg :

```sql
CREATE FOREIGN TABLE IF NOT EXISTS ign.ft_bdtopo_aerodromes(
    cleabs text,
    categorie text,
    nature text,
    usage text,
    toponyme text,
    statut_du_toponyme text,
    fictif boolean,
    geom geometry(MultiPolygon,4326)
)
    SERVER geoplateforme_ign
    OPTIONS (layer 'BDTOPO_V3:aerodrome');
```

But when I try to create a materialized view on it, the geom column of the materialized view is systematically full of NULL values. All other columns are fine. `geometry_columns`  is correctly declared, but the geom is populated with NULL. 

```sql
CREATE MATERIALIZED VIEW ign.vm_bdtopo_aerodromes AS (
SELECT  
    toponyme,
    geom
FROM ign.ft_bdtopo_aerodromes);
```

Tried with both 
https://data.geopf.fr/wfs
and
https://georisques.gouv.fr/services

By selecting *, or specifically geom, casting geom to geometry again in the materialized view, with LIMIT 1...

OS : fedora 41
Postgresql version : 17
Postgis 3.5.0
SELECT ogr_fdw_version() give :
OGR_FDW='1.1' GDAL='3.9.2'

**Comment by pramsey** [comment]
Hm, my backend just crashed on your test. So something is amiss.

**Comment by pramsey** [comment]
It's tied up with #83 in some way, but a pretty odd one, since it is very hard to exercise. I haven't been able to figure out a single set of commands that always gets me the condition.

**Comment by thomas-szczurek** [comment]
Screenshots for reference

![select_geom_ft](https://github.com/user-attachments/assets/bea6a4c9-f8e5-482f-bc8b-54afd1c9ec7e)
![view_creation](https://github.com/user-attachments/assets/1b4c65b8-7e46-412c-813a-f8b510c950c3)
![select_geoom_vm](https://github.com/user-attachments/assets/d2ab7ae2-9066-4f66-a238-d8bec6006188)

**Comment by pramsey** [comment]
I am finding that if I ensure the extension library is loaded before running the create materialized view, I get the right answers in the view. So I run `select * from ign.ft_bdtopo_aerodromes limit 1;` first, then run the MV creation. Another clue. The lookup of the geometry type Oid seems to fail when it's happening very early in the execution cycle.

**Comment by pramsey** [comment]
Trimmed it down a little more. `TypenameGetTypid("some_custom_type")` returns InvalidOid at all times when called within `CREATE MATERIALIZED VIEW`. This isn't an "on startup" issue, it's an interaction between this internal function and this internal command. Oddly `CREATE TABLE ... AS ...` does not have the same issue, though it's the closest analogue to `CREATE MATERIALIZED VIEW`.

**Comment by pramsey** [comment]
And now know that `CREATE MATERIALIZED VIEW` (or rather, `REFRESH`) sets the search_path very very narrowly, preventing `TypenameGetTypid` from finding the geometry type. So the answer is to rewrite the type old lookup to work at bare metal, first looking up the extension Oid, get the extension namespace, then lookup the type Oid in that namespace.

**Comment by pramsey** [comment]
Thanks @thomas-szczurek that was a very tricky one, but worthwhile fixing, as I imagine a lot of people use materialized views in production to buffer out FDW reliability and performance issues.

**Comment by thomas-szczurek** [comment]
Wow. I woke up this morning with a thank you from mister Paul Ramsey. This is a beautiful day !

**Comment by stefan-overkamp** [comment]
Many thanks, for investing this. It solved my problem after upgrading to PostgreSQL17 too.
