### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by devrimgunduz** [pramsey/pgsql-ogr-fdw#27]
Hi,

Can you please release a tarball, so that I can build RPMs of pgsql-ogr.fdw?

Thanks!
Regards, Devrim

**Comment by robe2** [comment]
Devrim that would be so cool to have that available on CentOS.

**Comment by devrimgunduz** [comment]
That is what I am still looking for...

**Comment by pramsey** [comment]
Sorry, try this https://github.com/pramsey/pgsql-ogr-fdw/releases/tag/v0.1
