### ISSUE TITLE
ERROR: ...undefined symbol: OGR_FD_GetGeomFieldCount

### ISSUE THREAD

**Issue by tryggvit** [pramsey/pgsql-ogr-fdw#28]
Ubuntu 14.04 LTS
gdal-config --version : 1.11.2
psql --version : psql (PostgreSQL) 9.3.6

The extension built and installed normally.
When trying to enable the ogr_fdw extension, I am running into an error:

create extension ogr_fdw;
ERROR:  could not load library "/usr/lib/postgresql/9.3/lib/ogr_fdw.so": /usr/lib/postgresql/9.3/lib/ogr_fdw.so: undefined symbol: OGR_FD_GetGeomFieldCount

**Comment by pramsey** [comment]
You almost certainly have two versions of GDAL on your computer, one of them older which is getting linked before the new one. Run a `find / -name 'libgdal*'` and see.

**Comment by tryggvit** [comment]
Thank you, that was exactly the problem :)
Removed the older version and everything works.
