### ISSUE TITLE
release number 0.1 disagrees with extension version 1.0

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#30]
I know I'm really being petty here, but I suspect other package maintainers will complain, so best you here it first from your ol' pal.

Here: https://github.com/pramsey/pgsql-ogr-fdw/releases  you have release as 0.1

BUT the extension install reads 1.0.

There is a bit of a disconnect here no? Now since you can't go backwards, you should just call it 1.0.1 or something

**Comment by pramsey** [comment]
Oh FFS... can I just blow away the tag and try again?

**Comment by robe2** [comment]
Works for me.  Might want to ask devrim for opinion.
