### ISSUE TITLE
make clean does not remove ogr_fdw_info

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#31]
When I do a make clean

All the .o files and .dll are gone, but ogr_fdw_info.exe still remains.  And compiling as a result doesn't rebuild the .exe.  Discovered this when testing my 32-bit and it didn't work.

**Comment by pramsey** [comment]
Fixed at 8b8cbdbe7bbd3a843391fd651dc04b835e1967a9
