### ISSUE TITLE
Should I be concerned or ignore - NOTICE:  unsupported OGR FDW expression type, T_ScalarArrayOpExpr

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#33]
I don't remember seeing this notice until recently.  I'm guessing it's harmless since the results look okay, but just wanted to make sure:

```
NOTICE:  unsupported OGR FDW expression type, T_ScalarArrayOpExpr

```

I get the above when doing something like

```
SELECT a, b
FROM c
WHERE b NOT IN ('1','2','3');
```

I assume that just means the query had to be done in postgres because OGR doesn't support IN? Get same notice with IN.  This is against an MS Access db.

**Comment by pramsey** [comment]
Shouldn't be worried, it's just warning about quals it doesn't understand. Like you said, only effect is that they won't get pushed down.
