### ISSUE TITLE
ogr_fdw odbc access to Foxpro

### ISSUE THREAD

**Issue by Linn111** [pramsey/pgsql-ogr-fdw#36]
I am running Windows 7 64-bit, but have posgresql -32-bit installed.  I installed ogr_fdw from http://www.postgresonline.com/downloads/fdw_win32_94_bin.zip (not sure who compiled this version for Windows).
 
I have successfully connected to an old Microsoft Visual Foxpro database using a 32-bit odbc DSN.  This same database attaches just fine via odbc to a Microsoft Access 2002 front end.  It also appears to work when attached to postgresql via ogr_fdw, except that there seems to be some strange datatype mismatching going on.
 
In the postgresql examples below flag2 is specified as flag2 varchar(1) and fid is specified as fid integer.  These definitions match the specifications in the Visual Foxpro database. When I run the following query, I get a null result, which is incorrect.
 
Testdb=# SET client_min_messages = debug;
SET
Testdb=# Select fid, desc_int,  flag1,  flag2
Testdb-#        from "table_$" where flag2 = 'N' and fid = 1;
DEBUG:  OGR SQL: (flag2 = 'N') AnD (fid = 1)
 fid | desc_int | flag1 | flag2
-----+----------+-------+-------
(0 rows)

**Comment by robe2** [comment]
You may just want to close this out as not enough information.  First of all he should have been using the shapefile driver for Foxpro instead of ODBC as that's more tailored for it and he doesn't have the version of foxpro.
