### ISSUE TITLE
ogr_fdw can't deal with correlated subselects

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#39]
I'm sure you probably know this, so consider it a feature enhancement request.
I noticed the TDS FDW driver has a similar issue, though it just returns null instead of throwing an error, which is less nice.

Here is a really lame example to demonstrate with your sample data.

```
SELECT name, age, (SELECT geom FROM pt_two AS t where t.name = p.name limit 1) As geom 
FROM 
pt_two As p;

```

Give error:

```
ERROR:  got into ogrDeparseParam code
********** Error **********

ERROR: got into ogrDeparseParam code
SQL state: XX000
```

**Comment by pramsey** [comment]
What's less nice, getting null or getting an error? Not sure if I can just no-op this problem away in the de-parsing code or not.
