### ISSUE TITLE
Tagged release 1.1?

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#48]
Can we have a tagged release so have release that works with 9.5.

**Comment by pramsey** [comment]
Oy vey. So here's the thing. Thanks to the magic of the extension framework, each new version number means we have to have an upgrade script as well as a normal script. God I hate that. Or a bunch of ugly junk to auto generate same (as in PostGIS). Hate that too. We have a bad situation, one in which version numbers, contrary to most experience, are *not* free.

**Comment by pramsey** [comment]
Would 1.0.1 do?

**Comment by robe2** [comment]
Yah that works for me.

**Comment by pramsey** [comment]
Done https://github.com/pramsey/pgsql-ogr-fdw/releases/tag/v1.0.1
