### ISSUE TITLE
JOIN pushdown possible?

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#49]
Excerpted from 9.5.0 release today

``
Foreign Data Wrappers (FDWs): These already allow using PostgreSQL as a query engine for other Big Data systems such as Hadoop and Cassandra. Version 9.5 adds IMPORT FOREIGN SCHEMA and JOIN pushdown making query connections to external databases both easier to set up and more efficient.
``

Is that possible to do with gdal?  If it isn't feel free to close this out.  It's probably only relevant for some datasources anyway.

**Comment by pramsey** [comment]
GDAL doesn't provide a native facility for joins, so any "join pushdown" would have to be implemented in the ogr_fdw itself. Probably better to just have two FDW tables and join locally. Only exception might be SQL-backed drivers, but that's basically pushing SQL at the native end points. So for those you're better off using the native FDW drivers and pushing the devs there to implement join pushdown.
