### ISSUE TITLE
doesn't compile against PostgresSQL 9.6 head

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#52]
I'll try to take a stab at fixing this when I have time.

Lots of warnings and these errors:

`
                              ^
ogr_fdw.c: In function 'ogrGetForeignPaths':
ogr_fdw.c:554:6: error: incompatible type for argument 3 of 'create_foreignscan_path'
      )
      ^
ogr_fdw.c:554:6: error: incompatible type for argument 6 of 'create_foreignscan_path'
      )
      ^
In file included from ogr_fdw.h:41:0,
                 from ogr_fdw.c:29:
c:/MING64~1/projects/POSTGR~1/rel/PG9~1.6W6/include/server/optimizer/pathnode.h:90:21: note: expected 'Cost' but argument is of type 'struct List *'
 extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,
                     ^
ogr_fdw.c:554:6: warning: passing argument 9 of 'create_foreignscan_path' from incompatible pointer type [enabled by default]
      )
      ^
In file included from ogr_fdw.h:41:0,
                 from ogr_fdw.c:29:
c:/MING64~1/projects/POSTGR~1/rel/PG9~1.6W6/include/server/optimizer/pathnode.h:90:21: note: expected 'struct Path *' but argument is of type 'struct List *'
 extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,
                     ^
ogr_fdw.c:554:6: error: too few arguments to function 'create_foreignscan_path'
      )
      ^
In file included from ogr_fdw.h:41:0,
                 from ogr_fdw.c:29:
c:/MING64~1/projects/POSTGR~1/rel/PG9~1.6W6/include/server/optimizer/pathnode.h:90:21: note: declared here
 extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,

In file included from ogr_fdw.h:41:0,
                 from ogr_fdw.c:29:
c:/MING64~1/projects/POSTGR~1/rel/PG9~1.6W6/include/server/optimizer/pathnode.h:90:21: note: expected 'struct PathTarget *' but argument is of type 'double'
 extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,
                     ^
ogr_fdw.c:554:6: error: incompatible type for argument 6 of 'create_foreignscan_path'
      )
      ^
In file included from ogr_fdw.h:41:0,
                 from ogr_fdw.c:29:
c:/MING64~1/projects/POSTGR~1/rel/PG9~1.6W6/include/server/optimizer/pathnode.h:90:21: note: expected 'Cost' but argument is of type 'struct List *'
 extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,
                     ^
ogr_fdw.c:554:6: warning: passing argument 9 of 'create_foreignscan_path' from incompatible pointer type [enabled by default]
      )
      ^
In file included from ogr_fdw.h:41:0,
                 from ogr_fdw.c:29:
c:/MING64~1/projects/POSTGR~1/rel/PG9~1.6W6/include/server/optimizer/pathnode.h:90:21: note: expected 'struct Path *' but argument is of type 'struct List *'
 extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,
                     ^
ogr_fdw.c:554:6: error: too few arguments to function 'create_foreignscan_path'
      )
      ^
In file included from ogr_fdw.h:41:0,
                 from ogr_fdw.c:29:
c:/MING64~1/projects/POSTGR~1/rel/PG9~1.6W6/include/server/optimizer/pathnode.h:90:21: note: declared here
 extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,

`

Evidentally I guess something changed upstream in createForeignPath

**Comment by pramsey** [comment]
I only had one small error, fixed with 9ae43f0
