### ISSUE TITLE
IMPORT FOREIGN SCHEMA option to exclude columns

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#53]
Now that you support not bringing in all columns, it would be great if we had a feature to exclude certain named columns.  For example FID for many data sources such as spreadsheets and ODBC sources is always included, and it's a made up thing that wasn't even in my original data.  I'd like to get rid of it since it sometimes doesn't even play well with querying like fid >2 returns nothing.

The format would be something like below and this is a real use case I have in mind.  ESRI stuffs in these useless area and length columns I don't need cause I can always recompute if I really wanted them.

```
CREATE SERVER svr_shps
   FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (datasource '/data',format 'ESRI Shapefile'); 

IMPORT FOREIGN SCHEMA ogr_all FROM SERVER svr_shps INTO staging
 OPTIONS(exclude_columns 'fid, shape_area, shape_leng');

```

**Comment by pramsey** [comment]
Do I have to handle column names that have commas in them? quoted column names in general? work like the table lists (expect user to provide the laundered equivalents?) etc? Man things get ugly with the laundering stuff in the way.

**Comment by robe2** [comment]
Hadn't thought about that.  I suppose OPTIONS don't allow for arrays? So we could just have people specify the unlaundered name (or have that dependent on if laundering is on or off)

**Comment by robe2** [comment]
Duh I feel so stupid, never realized you could just drop columns in a foreign table and now that you don't need all the columns, works fine doing that on ogr_fdw table.  So if this is too much trouble, you have my permission to can it.

I'm just going to do this from now on.

```
CREATE SCHEMA legacy;


IMPORT FOREIGN SCHEMA "dbo."
    FROM SERVER svr_sql INTO legacy;


DO language 'plpgsql'
$$
DECLARE var_sql text;
BEGIN 
var_sql := (SELECT string_agg('ALTER FOREIGN TABLE ' || quote_ident(table_schema) || '.' || quote_ident(table_name) || ' DROP COLUMN ' || column_name , ';')
FROM information_schema.columns AS c
WHERE c.table_schema = 'legacy' AND c.column_name LIKE 'geom');

IF var_sql > '' THEN
EXECUTE var_sql;
END IF;

END ;
$$

```
