### ISSUE TITLE
IMPORT FOREIGN SCHEMA can't handle SQL reserved words in column names

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#57]
Did you by chance get rid of the quote_ident I put in for import schema?  With my fresh pot of ogr_fdw, I can no longer import my OSM files.

 `NOTICE:  Number of tables to be created 5

ERROR:  syntax error at or near "natural"
LINE 22:  natural varchar,
          ^
QUERY:  CREATE FOREIGN TABLE multipolygons (
 fid integer,
 geom geometry,
 osm_id varchar,
 osm_way_id varchar,
 name varchar,
 type varchar,
 aeroway varchar,
 amenity varchar,
 admin_level varchar,
 barrier varchar,
 boundary varchar,
 building varchar,
 craft varchar,
 geological varchar,
 historic varchar,
 land_area varchar,
 landuse varchar,
 leisure varchar,
 man_made varchar,
 military varchar,
 natural varchar,
 office varchar,
 place varchar,
 shop varchar,
 sport varchar,
 tourism varchar,
 other_tags varchar
) SERVER osm_dc
OPTIONS (layer 'multipolygons');
********** Error **********

ERROR: syntax error at or near "natural"
SQL state: 42601`

**Comment by pramsey** [comment]
Reduce to tiny shape file I can add to the regression suite?

**Comment by robe2** [comment]
[natural.zip](https://github.com/pramsey/pgsql-ogr-fdw/files/232687/natural.zip)

This should also take care of the Integer64 test, though I couldn't verify since it fails to import and this file imports fine in ogrfdw 1.0.1

**Comment by robe2** [comment]
This won't handle the Integer64 regress  test, so maybe I should just make a small regress of that.  For this the bigint export came in as reals so had no issue querying (if I renamed natural to nat)
