### ISSUE TITLE
Regress fails on PG below 9.5

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#69]
I hate to be a bug about this, but 9.3 and 9.4 no longer pass regression. Because of the IMPORT FOREIGN SCHEMA.test.

Is there an easy way to disable a test?

**Comment by pramsey** [comment]
No, there isn't w/o adding a bunch of build cruft ala PostGIS. I'd rather take the test out, frankly.

**Comment by pramsey** [comment]
Or maybe just have the test regime be 9.5+

**Comment by pramsey** [comment]
I think: just test on 9.5 is going to be the mantra.
