### ISSUE TITLE
ERROR:  FDW table includes more geometry columns than exist in the OGR source regression failure

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#74]
I'm having a bunch of regressions using ODBC data sources.  Here is one of them.

```
CREATE SERVER northwind
  FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
    datasource 'C:/fdw_data/northwind.mdb',
    format 'ODBC' );

IMPORT FOREIGN SCHEMA ogr_all FROM SERVER northwind INTO public;

````

Works fine.  But when I go to categories table, which happens to have bytea (which is an MS Access Picture blob)

```

SELECT * FROM categories;

```

>  ERROR: FDW table includes more geometry columns than exist in the OGR source
SQL state: XX000

This used to work in ogr_fdw 1.0.1.  I'll retest on my 9.5 newer build just to confirm it's not a 9.6 issue (I have more serious issues with ODBC issue , which might have to do with the config options stuff.  Those I'm investigating.

Both ogr_fdw 1.0.1 and master generate the same foreign table structure for categories which looks like:

```

CREATE FOREIGN TABLE public.categories
   (fid integer ,
    geom bytea ,
    categoryid integer ,
    categoryname character varying ,
    description character varying ,
    picture bytea )
   SERVER northwind
   OPTIONS (layer 'Categories');

```

So must be in the reading where it goes south.

I tested with and without loading postgis.  Only difference is that geom comes in as geometry instead of bytea (as expected).  Still same error though.

**Comment by robe2** [comment]
FWIW I can get around the issue by changing foreign table to exclude geom bytea or picture bytea.

geom doesn't actually exist in the table anyway, but OGR ODBC has a long standing issue that it always throws a bogus geometry column in there even when one doesn't exist.

**Comment by rouault** [comment]
From what I see from the code, if you install the postgis extension, that should solve the issue since the 'geom' column will properly be declared as 'geometry'. In the case postgis isn't loaded, the code will currently not distinguish geometry columns from binary columns

**Comment by robe2** [comment]
@rouault  Ah indeed you are right.  i was testing on ogrfdw 1.0.1 to confirm it worked with or without installing postgis.and I could query in either case.

After recent changes, I can't even import northwind without installing postgis. Get this error if I don't have postgis installed.

```
NOTICE:  Number of tables to be created 26


ERROR:  type "geometry" does not exist
LINE 3:  geom geometry,
              ^
QUERY:  CREATE FOREIGN TABLE categories (
 fid integer,
 geom geometry,
 categoryid integer,
 categoryname varchar,
 description varchar,
 picture bytea
) SERVER northwind
OPTIONS (layer 'Categories');
CONTEXT:  importing foreign table "categories"
********** Error **********

ERROR: type "geometry" does not exist
SQL state: 42704
Context: importing foreign table "categories"

```

**Comment by robe2** [comment]
I'm pretty sure I had code in IMPORT FOREIGN SCHEMA logic to use bytea if postgis was found to not be installed.  @pramsey  must have taken that logic out.

**Comment by pramsey** [comment]
Here's a wraparound recipe that does the same thing
```
CREATE SERVER pgserver
  FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
    datasource 'PG:dbname=contrib_regression host=localhost',
    format 'PostgreSQL' );

CREATE TABLE bytea_local (
  fid integer primary key,
  name varchar,
  geom bytea,
  age bigint,
  bin bytea,
  happened time
);
INSERT INTO bytea_local VALUES 
  (1, 'Jim', '14232'::bytea, 8142312312, '99999'::bytea, '13:23:21'::time);
INSERT INTO bytea_local VALUES 
  (2, 'James', '55555'::bytea, 9124231543, '88888'::bytea, '15:55:55'::time);
  
CREATE FOREIGN TABLE bytea_fdw (
  fid integer,
  name text,
  geom bytea,
  age bigint,
  bin bytea,
  happened time
) SERVER pgserver OPTIONS (layer 'bytea_local');
```

**Comment by robe2** [comment]
Hmm the error I complained about with:

```
NOTICE:  Number of tables to be created 26


ERROR:  type "geometry" does not exist
LINE 3:  geom geometry,
              ^
QUERY:  CREATE FOREIGN TABLE categories (
 fid integer,
 geom geometry,
 categoryid integer,
 categoryname varchar,
 description varchar,
 picture bytea
) SERVER northwind
OPTIONS (layer 'Categories');
CONTEXT:  importing foreign table "categories"
********** Error **********

ERROR: type "geometry" does not exist
SQL state: 42704
Context: importing foreign table "categories"

```

is gone, but back to the original that even with two byteas it doesn't work (which it loks like @pramsey  replicated. 

I guess my last error about it complaining about geometry type not existing was because I dropped postgis in the same connection as I was importing, so guess that's just a cache lookup issue.

**Comment by pramsey** [comment]
Need to try PR #76, @robe2

**Comment by robe2** [comment]
Yap that fixes the issue for both with postgis and without postgis installed.

**Comment by pramsey** [comment]
Yay! PR merged.
