### ISSUE TITLE
ODBC Oracle regression

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#75]
Okay I think my second regression, might be something I just need to be aware of.

I have an ODBC connection to Oracle which looks something like below which used to work in ogr_fdw 1.0.1

```

DROP SERVER IF EXISTS bloomington_filter CASCADE;
CREATE SERVER bloomington_filter
  FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
    datasource 'ODBC:a/b@orac_server,SYS.ALL_TABLES,GIS.TABLE_MIGRATION,SYS.ALL_TAB_COLUMNS,SYS.ALL_CONSTRAINTS,SYS.ALL_CONS_COLUMNS,SYS.ALL_VIEWS',
    format 'ODBC' );

```

and the error halts my Postgres instance (and on the PostgreSQL windows server box a dialog pops up saying)

```

Internal error - unable to initialize NLS during driver load

```

I suspect this has to do  with the addition of new encoding feature, so maybe I'm missing an env variable switch somewhere.  I'll test with SQL Server next to see if I have the same issue.

**Comment by pramsey** [comment]
Any further information on this one?

**Comment by robe2** [comment]
I tested against a SQL Server database and that seems to work fine.  So it's these extra annoying settings I have to set for Oracle like ORACLE_HOME,TNS_ADMIN  and what not. I haven't investigated yet where that is supposed to go but I porbably have it set wrong.
Briefly summarized here.

https://community.oracle.com/thread/2398556?tstart=0

I suspect if I set it right it would be fine.  Still might be nice to be able to disable encoding check (or can you?).

**Comment by pramsey** [comment]
Not sure what encoding check you're referring to?

There's one at the very top that ensures that your PgSQL database is UTF-8, so we can pass strings to/from OGR without transcoding. Some of the OGR drivers have transcoding options so you can transcode non-UTF8 sources inside OGR (like the shape file example in the regression suite).

**Comment by robe2** [comment]
Hmm well this is mighty annoying and interesting. On my workstation doing ODBC to Oracle works fine with ogrfdw branch. But copying my pg9.6 instance  to my server, it doesn't work. But my 9.5 Oracle ODBC connection ot oracle with ogrfdw 1.0.1 is happily working on the server.

I have both services running with elevated permissions so I assume that's not the issue.  Only difference between my server and my workstation is I have Oracle development and the full client shebang installed on my workstation.

I guess I need to investigate this more by maybe building ogrfdw master against 9.5 and swapping out the 1.0.1 that works with this to rule out somethign special about my postgres config security on the server.

**Comment by robe2** [comment]
Okay if I build for 9.5 and swap out my ogrfdw 1.0.1 with the just built one, doing oracle import foreign schema and creating the foreign server works fine.  So must be something with my 9.6 instance at fault and only at fault on the server like I forgot to copy over a dll.
