### ISSUE TITLE
Can't always select by fid

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#77]
While I'm complaining about stuff, I think this has always been an issue.

If I have an excel or open office spreadsheet which the fid is a fake sequential.

I can't do this:

```

SELECT * 
     FROM budget.form_5___monthly_cash_flow 
     WHERE fid = 2;

```

So I have to resort to doing this:

```

WITH c AS (SELECT * FROM budget.form_5___monthly_cash_flow)
SELECT * FROM c WHERE fid = 2;

```

I'm assuming is because the fid is being created on the fly so that's just the way it is.  It's just not intuitive. I haven't tried but I bet if fid is coming from a real column (like a pkey) I might be able to select from it.

**Comment by pramsey** [comment]
I cannot replicate this with a simple CSV test. I've added the test to regression at 285e5fb, and you can try for yourself. It might be an OGR thing, @rouault?
