### ISSUE TITLE
Regress doesn't work if GDAL not compiled with PostgreSQL

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#80]
It's really hard for me to regress test now since you added a PostgreSQL wrapper test.  Any chance you can remove that.

I don't build GDAL with PostgreSQL support since I rely on the libpq.dll shipped by EDB, and I don't want to have to build 6 (32-bit, 64-bit for 9.4-9.6) different versions of GDAL just to be safe.

I know I could risk it and build with the lowest PostgreSQL version, but that is playing a little too deep for me.

**Comment by pramsey** [comment]
Yeah, I was wondered about that, since not all GDALs have PgSQL support. Kind of a shame, since wraparound is the easiest way to exercise various scenarios of types/tables/names/etc.

**Comment by robe2** [comment]
well the file access thing there is no way around since that needs to be tested as common use case.

Perhaps a switch for extended tests.  Then you could even move the pg 9.5 import foreign into that bucket. The extended would be something useful to run for big code changes to verify you didn't regress, but not for the common user compiling and doing a quick confirm.

**Comment by pramsey** [comment]
With PR #82, it is easier to turn bits on/off

**Comment by robe2** [comment]
Works for me.
