### ISSUE TITLE
OPTION updatable to make foreign table readonly

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#86]
I presume you haven't added that yet.  I think we might want it.  Some people don't want their table's updateable.

e.g. for example I just experimented with updating an OpenOffice Spreadsheet and it sorta worked, but it converted all the formulas to plain numbers.  That's more telling of the ODS driver than this, but...  you know postgres_fdw has such an option you set with:

`ALTER FOREIGN TABLE ft_facts OPTIONS (ADD updatable 'false');`

so probably good to have the same thing.

http://www.postgresql.org/docs/9.5/static/postgres-fdw.html

**Comment by pramsey** [comment]
Good plan. Default to read only?

**Comment by robe2** [comment]
Hmm well postgres_fdw defaults to true.  I think its okay to leave it true for default as long as people can turn it off per table or per server.

For example the postgres_fdw you can set the option at the server level too

```

ALTER FOREIGN SERVER fs_prod OPTIONS (ADD updatable 'false');

```

and all tables on that server inherit the setting unless they override it with their own.
