### ISSUE TITLE
RETURNING doesn't return new id

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#88]
This might be expected behavior or just specific to driver, but thought I'd flag it since it's non-standard behavior for a table.

I have a folder of shape files, one of which is airports

```
CREATE SERVER svr_shp FOREIGN DATA WRAPPER ogr_fdw
OPTIONS (datasource 'C:/fdw_data/gisdata',
 format 'ESRI Shapefile'
);
CREATE SCHEMA shps;
-- this is a PostgreSQL 9.5 feature
IMPORT FOREIGN SCHEMA ogr_all
FROM SERVER svr_shp INTO shps;

```

When I do this

```
INSERT INTO shps.airports(locid, geom)
SELECT 'ROO', geom
FROM shps.airports
WHERE locid = 'BOS' RETURNING fid, locid,ST_AsText(geom);

```

I get this: 

```
 fid | locid |                 st_astext
-----+-------+-------------------------------------------
     | ROO   | POINT(-71.0064166666667 42.3629722222222)
(1 row)
```

So I thought maybe fid isn't being assigned, or maybe it isn't and it just regenerates during the query.  
If I do:

```
SELECT fid, locid FROM shps.airports 
WHERE locid = 'ROO';
```
I get

```
  fid  | locid
-------+-------
 19952 | ROO
(1 row)
```

and it seems not to reuse the fids since I can delete ROOs and if I insert again I get 19953.

**Comment by pramsey** [comment]
Should be fixed at f6bd011
