### ISSUE TITLE
encoding issue on 64-bit PostgreSQL 9.3-9.5 Windows

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#90]
This might require no fixing on your end, could be an issue on my end.

Which version of PostgreSQL are you building against?

When I was building against 9.5.1 the file test was passing (against GDAL 2.0.2) both against 9.5.1 mingw64-w64 and 9.5.1 EDB.  But winnie was failing, so I upgrade my build to 9.5.2 to agree with hers
and now my local is failing.  My 9.6devl 64-bit is fine.

I can't see what's different aside from the micro version.

Anyrate on winnie the file tests are consistently failing for 9.3-9.5 64-bit but pass for the 9.3-9.5 32-bit chain.

I'll investigate more to confirm the versions of the 32-bit and any others I could see.

Would be interesting though if you are not compiling against 9.5.2 (latsts stable), if upgrading makes this fail for you as well then that would point at a recent change in the PostgreSQL micros.

The failure looks like this:

`
SET client_min_messages = debug1;  
SELECT * FROM e_1 WHERE fid = 1;
DEBUG:  GDAL config option 'SHAPE_ENCODING' set to 'LATIN1'
DEBUG:  OGR SQL: (fid = 1)
DEBUG:  GDAL config option 'SHAPE_ENCODING' set to 'LATIN1'
 fid | name 
-----+------
   1 | Pul
(1 row)
`
Getting that instead of expected

`
SET client_min_messages = debug1;  
SELECT * FROM e_1 WHERE fid = 1;
DEBUG:  GDAL config option 'SHAPE_ENCODING' set to 'LATIN1'
DEBUG:  OGR SQL: (fid = 1)
DEBUG:  GDAL config option 'SHAPE_ENCODING' set to 'LATIN1'
 fid | name 
-----+------
   1 | Pàul
(1 row)
`

**Comment by pramsey** [comment]
I'm on 9.5.1, everything regresses OK. You say things will break at 9.5.2?

**Comment by robe2** [comment]
Well that is a possible suspicion.  9.5.1 worked for me on my local, but then when I flipped to testing against 9.5.2 to agree with winnie's build version, that's when things stopped working.  Only change to my compile script was switching from 9.5.1 to 9.5.2 (for postgresql install) and testing both 9.5.2 edb and mingw.

Why 9.6 development works is a mystery.  I was going to test next against 9.5 branch (unreleased) to see if that works.

**Comment by pramsey** [comment]
9.5.2 works fine for me too

**Comment by robe2** [comment]
Hmm okay might be something different I missed between the two or I'm just f..ked cause I'm on windows and no one cares about windows users.

**Comment by robe2** [comment]
Well the good or bad news however you look at it is I managed to break my 9.6 in same way as well when I upgraded to GDAL 2.1.0, though downgrading doesn't fix the issue.  I must have a messed up iconv path setting somewhere.

**Comment by robe2** [comment]
Okay problem solved.  I took libiconv out of my LDPATH during GDAL compile and that seems to have fixed the issue.  cross fingers.  i guess I didn't compile the 32-bit ones that way.
