### ISSUE TITLE
Not possible to query royally screwed up geometries

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#91]
Feel free to dismiss this one if you want as I'm not sure there is much that can be done about this.

Created fdw as usual using this file - https://s3.amazonaws.com/metro-extracts.mapzen.com/raleigh_north-carolina.osm.pbf

```
CREATE FOREIGN SERVER svr_osm

CREATE SERVER svr_osm
   FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (datasource 'C:/fdw_data/raleigh_north-carolina.osm.pbf',format 'OSM');

CREATE SCHEMA IF NOT EXISTS osm;
IMPORT FOREIGN SCHEMA ogr_all 
FROM SERVER svr_osm INTO osm;

```
When to go get me some multipolygons

```
CREATE TABLE raleigh_polys AS 
SELECT osm_id, name, type, geom, 
    other_tags::hstore, admin_level, building, boundary
FROM osm.multipolygons
WHERE ST_IsValid(geom);
```

and bammo I can not pass go.

```

NOTICE:  unsupported OGR FDW expression type, T_FuncExpr
NOTICE:  Self-intersection at or near point -78.94407972131232 35.759430367365631
NOTICE:  Self-intersection at or near point -78.577156551212369 35.812093724724676
NOTICE:  Self-intersection at or near point -78.901625499641654 36.050391062136747
NOTICE:  Self-intersection at or near point -79.043338700000007 35.937768900000002
NOTICE:  Self-intersection at or near point -78.622104800000002 35.8749398


ERROR:  Polygon must have at least four points in each ring
********** Error **********

ERROR: Polygon must have at least four points in each ring
SQL state: XX000

```

I'm thinking this is because of our policy on PostGIS and not really an ogr_fdw issue, but just wanted to confirm.

**Comment by pramsey** [comment]
It's a PostGIS policy, but it's also an outgrowth of the functions I'm using to process the input WKB data from OGR. I'm not sure I can get around it. I use the 'recv' functions to handie the incoming binary WKB. If I changed to convert the OGR binary into Hex and then used the 'input' function, I think it would work OK. Have to confirm. Bit of a bad scene though, fluffing up the data before ingesting.

**Comment by pramsey** [comment]
Yeah, confirmed in the PostGIS code base: the recv function runs with `LW_PARSER_CHECK_ALL` while the input function runs with `LW_PARSER_CHECK_NONE` when fed hex WKB. So, what's more important, performance or accepting broken geoms?

**Comment by robe2** [comment]
I think performance.  Was more of a curiosity than anything. As Sandro would say, would be nice to give users an option, but I'm not Sandro, I just pretend to be one sometimes. :)

**Comment by pramsey** [comment]
I was thinking accepting brokens might be better, as things are pretty slow already... OGR could be hooked up to all sorts of data sources, like shape files, that are happy w/ bad geometries.

**Comment by pramsey** [comment]
I suppose Yet Another Configuration Option is also possible.

**Comment by pramsey** [comment]
@robe2 maybe try #93. It's less efficient, but probably more useful.

**Comment by robe2** [comment]
Marvelous:

```
-- 19.7 secs to get in 166,702 rows (lets in only valid)
-- 4.5 secs without ST_IsValid check (166,774 rows)
CREATE TABLE raleigh_polys AS 
SELECT  osm_id, name, type, geom::geography As geog,
    other_tags::hstore, admin_level, building, boundary
FROM osm.multipolygons 
WHERE ST_IsValid(geom);

```
