### ISSUE TITLE
geom as bytea is null if postgis is installed

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#92]
I think this is a bug.

If I don't have PostGIS installed, I get a table like this which is fine and what I expect.

```
CREATE FOREIGN TABLE osm.multipolygons
   (fid bigint ,
    geom bytea ,
    osm_id character varying ,
    osm_way_id character varying ,
    name character varying ,
    type character varying ,
    aeroway character varying ,
    amenity character varying ,
    admin_level character varying ,
    barrier character varying ,
    boundary character varying ,
    building character varying ,
    craft character varying ,
    geological character varying ,
    historic character varying ,
    land_area character varying ,
    landuse character varying ,
    leisure character varying ,
    man_made character varying ,
    military character varying ,
    "natural" character varying ,
    office character varying ,
    place character varying ,
    shop character varying ,
    sport character varying ,
    tourism character varying ,
    other_tags character varying )
   SERVER svr_osm
   OPTIONS (layer 'multipolygons');

```

and when I query it like this:

```
SELECT osm_id, geom FROM osm.multipolygons ORDER BY osm_id limit 10;

```
I see data in some  geom columns and confirm geom is null  (returns false)

```
\001\006\000\000\000\001\000\000\000\001\003\000\000\000\003\000\000\000\011\000\000\000\3268\233\216\000\273S\300\253\007\314C\246\000B@\331\013`%\372\272S\300x\320\354\272\267\000B@v\200q\272\366\272S\300\353\363br\264\000B@\317R\015V\367\272S\300\274G\354\311\262\000B@7\243\213\362\361\272S\300$\335\205\234\255\000B@\212\236J\274\362\272S\300\300\357:v\253\000B@*\011?'\363\272S\300\256<\222\334\253\000B@\346\250H*\370\272S\300t\01534\236\000B@\3268\233\216\000\273S\300\253\007\314C\246\000B@\005\000\000\000\366\326\033\020\374\272S\300\337\204\347J\251\000B@\020\340>\274\370\272S\300@k~\374\245\000B@\214Z\253\207\371\272S\300)w\237\343\243\000B@sQ\210\333\374\272S\300\310\220\0102\247\000B@\366\326\033\020\374\272S\300\337\204\347J\251\000B@\005\000\000\000\3544\322R\371\272S\300\246%\373\214\260\000B@dF.\356\365\272S\300~\204\253M\255\000B@\3031&X\367\272S\300\0112\247p\251\000B@\200\300^\274\372\272S\3001\323\366\257\254\000B@\3544\322R\371\272S\300\246%\373\214\260\000B@

```

Now if I then 

```
CREATE EXTENSION postgis;

```
Disconnect and reconnect to my database and run the same query

 I see no data in geom column.

Shouldn't bytea behave the same regardless whether I have postgis installed or not?

In fact all my geom columns are null now

```
SELECT osm_id, geom is null FROM osm.multipolygons ORDER BY osm_id limit 10;
``
returns true for all of them when PostGIS gets installed.

**Comment by pramsey** [comment]
I might have to won't-fix this one. Geometry columns often lack names in OGR, so I have no good means to distinguish between them and other things in trying to match up columns by name. Using types is the first best way, so if you have PostGIS, I look for geometry columns to match to. Would it kill you to just alter the type on your table?

**Comment by robe2** [comment]
I wasn't thinking about that use case as much as when I don't want a geometry column to be treated as such I would mark it as a bytea (basically overriding what import foreign schema says) .  Aren't you guessing when postgis is not installed? How am I getting data in that field otherwise?

Only reason for this would be for example to get around the postgis policy constraint about no less than 4 points for ring of geometry.  Even when I don't have geom in my column list (for table or select) if the offending record comes up it kills the query if I have postgis installed.

So hope would be to bring in as bytea with hope I could fix it by some other means.  Purely hypotehteical anyway so I won't be offended if you mark as wontfix.

**Comment by pramsey** [comment]
Yeah, sorry going to close this. Any "fix" would only make other things worse.
