### ISSUE TITLE
NOTICE:  failed to flush writes to OGR data source for CSV

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-ogr-fdw#94]
I think this may be only a windows issue as strk suggested.
(using GDAL 2.1.0)
Have you by chance tried updating a CSV file?  I think GDAL's write approach in GDAL 2.1.0 is to completely overwrite the file.  I'm suspecting it can't because well file in use.

So when I do something like

```
UPDATE jobsurvey SET gender = 'M' where lastname = 'SMITH' and gender = 'F'
RETURNING fid, gender, lastname;

```

I get notice:

```
NOTICE:  failed to flush writes to OGR data source
```

Though turning returns the changed data, but changed data never makes to file and I see a file called JobSurvey.csv_ogr_tmp.csv in same folder.which also doesn't have the new data.

**Comment by pramsey** [comment]
I have a different problem w/ my CSV data sources. INSERTs and DELETEs have effect and happen to the CSV file as well, but UPDATES never change anything, and INSERTS only add nulls. So, there's some work to be done here, much be a larger problem, perhaps I broke something when fixing the RETURNING issue INSERT.

**Comment by pramsey** [comment]
Confirmed, this is larger than a CSV issues, I cannot update Shape files anymore either. Something recent commits has had a bad knock-on effect. I'm going to add have to add some r/w tests to the wraparound pgsql code.

**Comment by pramsey** [comment]
After 8bef417 fixed by overall problems, I have run update/insert/delete SQL on a CSV and confirmed that the file reflects the table state at every step. So this is platform issue for you potentially, assuming you weren't seeing the same bug as me.

**Comment by pramsey** [comment]
Hoping regression tests added to pgsql at b2ff85d don't cause you trouble.

**Comment by robe2** [comment]
I have those tests disabled so I don't see them.  I used to be able to update ESRI Shape files about a week ago and now I can't.  Can you check if you can? If you can I'll downgrade my GDAL 2.1 upgrade to see if I'm able to again.

Last week, this worked great:

```

UPDATE shps.airports SET geom = ST_SnapToGrid(geom,0.00001)
WHERE locid = 'JFK';

```
and I could see the change when querying table.
With latest master, not so much.

I get this error:

```
ERROR:  failure populating OGR feature
HINT:  Unsupported WKB type 536870913
********** Error **********

ERROR: failure populating OGR feature
SQL state: HV000
Hint: Unsupported WKB type 536870913

```

As before when I tried last it correctly detects the geom field as geometry(Point,4326)

**Comment by pramsey** [comment]
No, everything is working fine for me in master, w/ shape files as well as postgresql loopbacks.
{{{
contrib_regression=# select * from pt_10;
 fid |                    geom                    
-----+--------------------------------------------
   0 | 0101000000C00497D1162CB93F8CBAEF08A080E63F
   1 | 010100000054E943ACD697E2BFC0895EE54A46CF3F
(2 rows)

contrib_regression=# update pt_10 set geom = st_snaptogrid(geom,0.00001) where fid = 1;
UPDATE 1
contrib_regression=# select * from pt_10;
 fid |                    geom                    
-----+--------------------------------------------
   0 | 0101000000C00497D1162CB93F8CBAEF08A080E63F
   1 | 01010000000FD6FF39CC97E2BF4B41B7973446CF3F
(2 rows)
}}}

**Comment by robe2** [comment]
Which gdal version are you using?

**Comment by robe2** [comment]
Okay I reverted to GDAL 2.0.2, recompiled and still same problem.  So why is it working for you now and not for me. Might be another Regina has too much going on case and is confused case.

I guess need to back track to the version that worked and see what's different.

**Comment by robe2** [comment]
One more thing I tried.  I deleted my .prj file so it can't detect an SRID anymore.  Reimported and it worked.  So seems to be being tripped up by the SRID detection.  Is your test table recognized with an SRID?

**Comment by robe2** [comment]
The csv is still an issue for me so I suspect sadly that Sandro is right and its because windows won'ta llow deletion of a file while it's in use and Linux does. So no fix for that as far as windows is concerned.  

for the ESRI shapefile should I open a separate ticket for that as that's a different issue.

**Comment by pramsey** [comment]
Bingo, you found it, when UPDATING a record where the table defn includes a geometry type with type/srid typmod, it fails
```
contrib_regression=# update pt_11 set geom = st_snaptogrid(geom,0.00001) where fid = 1;
ERROR:  failure populating OGR feature
HINT:  Unsupported WKB type 536870913
contrib_regression=# 
```
Opening a new ticket for this, and closing this CSV one out.
